// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package raft

import (
	mock "github.com/stretchr/testify/mock"
)

// newMocksourceNode creates a new instance of mocksourceNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksourceNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksourceNode {
	mock := &mocksourceNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocksourceNode is an autogenerated mock type for the sourceNode type
type mocksourceNode struct {
	mock.Mock
}

type mocksourceNode_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksourceNode) EXPECT() *mocksourceNode_Expecter {
	return &mocksourceNode_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type mocksourceNode
func (_mock *mocksourceNode) Config() Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 Config
	if returnFunc, ok := ret.Get(0).(func() Config); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(Config)
	}
	return r0
}

// mocksourceNode_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type mocksourceNode_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *mocksourceNode_Expecter) Config() *mocksourceNode_Config_Call {
	return &mocksourceNode_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *mocksourceNode_Config_Call) Run(run func()) *mocksourceNode_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mocksourceNode_Config_Call) Return(config Config) *mocksourceNode_Config_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *mocksourceNode_Config_Call) RunAndReturn(run func() Config) *mocksourceNode_Config_Call {
	_c.Call.Return(run)
	return _c
}

// GetState provides a mock function for the type mocksourceNode
func (_mock *mocksourceNode) GetState() RaftBlockState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 RaftBlockState
	if returnFunc, ok := ret.Get(0).(func() RaftBlockState); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(RaftBlockState)
	}
	return r0
}

// mocksourceNode_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type mocksourceNode_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
func (_e *mocksourceNode_Expecter) GetState() *mocksourceNode_GetState_Call {
	return &mocksourceNode_GetState_Call{Call: _e.mock.On("GetState")}
}

func (_c *mocksourceNode_GetState_Call) Run(run func()) *mocksourceNode_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mocksourceNode_GetState_Call) Return(raftBlockState RaftBlockState) *mocksourceNode_GetState_Call {
	_c.Call.Return(raftBlockState)
	return _c
}

func (_c *mocksourceNode_GetState_Call) RunAndReturn(run func() RaftBlockState) *mocksourceNode_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// NodeID provides a mock function for the type mocksourceNode
func (_mock *mocksourceNode) NodeID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NodeID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mocksourceNode_NodeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeID'
type mocksourceNode_NodeID_Call struct {
	*mock.Call
}

// NodeID is a helper method to define mock.On call
func (_e *mocksourceNode_Expecter) NodeID() *mocksourceNode_NodeID_Call {
	return &mocksourceNode_NodeID_Call{Call: _e.mock.On("NodeID")}
}

func (_c *mocksourceNode_NodeID_Call) Run(run func()) *mocksourceNode_NodeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mocksourceNode_NodeID_Call) Return(s string) *mocksourceNode_NodeID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mocksourceNode_NodeID_Call) RunAndReturn(run func() string) *mocksourceNode_NodeID_Call {
	_c.Call.Return(run)
	return _c
}

// leaderCh provides a mock function for the type mocksourceNode
func (_mock *mocksourceNode) leaderCh() <-chan bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for leaderCh")
	}

	var r0 <-chan bool
	if returnFunc, ok := ret.Get(0).(func() <-chan bool); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan bool)
		}
	}
	return r0
}

// mocksourceNode_leaderCh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'leaderCh'
type mocksourceNode_leaderCh_Call struct {
	*mock.Call
}

// leaderCh is a helper method to define mock.On call
func (_e *mocksourceNode_Expecter) leaderCh() *mocksourceNode_leaderCh_Call {
	return &mocksourceNode_leaderCh_Call{Call: _e.mock.On("leaderCh")}
}

func (_c *mocksourceNode_leaderCh_Call) Run(run func()) *mocksourceNode_leaderCh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mocksourceNode_leaderCh_Call) Return(boolCh <-chan bool) *mocksourceNode_leaderCh_Call {
	_c.Call.Return(boolCh)
	return _c
}

func (_c *mocksourceNode_leaderCh_Call) RunAndReturn(run func() <-chan bool) *mocksourceNode_leaderCh_Call {
	_c.Call.Return(run)
	return _c
}

// leaderID provides a mock function for the type mocksourceNode
func (_mock *mocksourceNode) leaderID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for leaderID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mocksourceNode_leaderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'leaderID'
type mocksourceNode_leaderID_Call struct {
	*mock.Call
}

// leaderID is a helper method to define mock.On call
func (_e *mocksourceNode_Expecter) leaderID() *mocksourceNode_leaderID_Call {
	return &mocksourceNode_leaderID_Call{Call: _e.mock.On("leaderID")}
}

func (_c *mocksourceNode_leaderID_Call) Run(run func()) *mocksourceNode_leaderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mocksourceNode_leaderID_Call) Return(s string) *mocksourceNode_leaderID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mocksourceNode_leaderID_Call) RunAndReturn(run func() string) *mocksourceNode_leaderID_Call {
	_c.Call.Return(run)
	return _c
}

// leadershipTransfer provides a mock function for the type mocksourceNode
func (_mock *mocksourceNode) leadershipTransfer() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for leadershipTransfer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mocksourceNode_leadershipTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'leadershipTransfer'
type mocksourceNode_leadershipTransfer_Call struct {
	*mock.Call
}

// leadershipTransfer is a helper method to define mock.On call
func (_e *mocksourceNode_Expecter) leadershipTransfer() *mocksourceNode_leadershipTransfer_Call {
	return &mocksourceNode_leadershipTransfer_Call{Call: _e.mock.On("leadershipTransfer")}
}

func (_c *mocksourceNode_leadershipTransfer_Call) Run(run func()) *mocksourceNode_leadershipTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mocksourceNode_leadershipTransfer_Call) Return(err error) *mocksourceNode_leadershipTransfer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mocksourceNode_leadershipTransfer_Call) RunAndReturn(run func() error) *mocksourceNode_leadershipTransfer_Call {
	_c.Call.Return(run)
	return _c
}
