version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    # Group all patch updates into a single PR
    groups:
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    allow:
      - dependency-name: "rollkit/*"
    labels:
      - T:dependencies
    # Group all patch updates into a single PR
    groups:
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    # Group updates across all go modules
    groups:
      go-dependencies:
        patterns:
          - "*"
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    allow:
      - dependency-name: "github.com/rollkit/*"
    labels:
      - T:dependencies
    # Group all patch updates into a single PR
    groups:
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: gomod
    directory: "/core"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    groups:
      go-dependencies:
        patterns:
          - "*"
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
  - package-ecosystem: gomod
    directory: "/da"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    groups:
      go-dependencies:
        patterns:
          - "*"
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
  - package-ecosystem: gomod
    directory: "/execution/evm"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    groups:
      go-dependencies:
        patterns:
          - "*"
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
  - package-ecosystem: gomod
    directory: "/sequencers/based"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    groups:
      go-dependencies:
        patterns:
          - "*"
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
  - package-ecosystem: gomod
    directory: "/sequencers/single"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    groups:
      go-dependencies:
        patterns:
          - "*"
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
  - package-ecosystem: gomod
    directory: "/apps/testapp"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    groups:
      go-dependencies:
        patterns:
          - "*"
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
  - package-ecosystem: gomod
    directory: "/apps/evm/single"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    groups:
      go-dependencies:
        patterns:
          - "*"
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
  - package-ecosystem: gomod
    directory: "/apps/evm/based"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    groups:
      go-dependencies:
        patterns:
          - "*"
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
  - package-ecosystem: gomod
    directory: "/test/e2e"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    groups:
      go-dependencies:
        patterns:
          - "*"
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
  - package-ecosystem: gomod
    directory: "/test/docker-e2e"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    groups:
      go-dependencies:
        patterns:
          - "*"
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    # Group all patch updates into a single PR
    groups:
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
