// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/celestiaorg/go-square/v3/share"
	"github.com/evstack/ev-node/pkg/da/jsonrpc"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBlobModule creates a new instance of MockBlobModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlobModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlobModule {
	mock := &MockBlobModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlobModule is an autogenerated mock type for the BlobModule type
type MockBlobModule struct {
	mock.Mock
}

type MockBlobModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlobModule) EXPECT() *MockBlobModule_Expecter {
	return &MockBlobModule_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockBlobModule
func (_mock *MockBlobModule) Get(context1 context.Context, v uint64, namespace share.Namespace, commitment jsonrpc.Commitment) (*jsonrpc.Blob, error) {
	ret := _mock.Called(context1, v, namespace, commitment)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *jsonrpc.Blob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, share.Namespace, jsonrpc.Commitment) (*jsonrpc.Blob, error)); ok {
		return returnFunc(context1, v, namespace, commitment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, share.Namespace, jsonrpc.Commitment) *jsonrpc.Blob); ok {
		r0 = returnFunc(context1, v, namespace, commitment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jsonrpc.Blob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, share.Namespace, jsonrpc.Commitment) error); ok {
		r1 = returnFunc(context1, v, namespace, commitment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobModule_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBlobModule_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - v uint64
//   - namespace share.Namespace
//   - commitment jsonrpc.Commitment
func (_e *MockBlobModule_Expecter) Get(context1 interface{}, v interface{}, namespace interface{}, commitment interface{}) *MockBlobModule_Get_Call {
	return &MockBlobModule_Get_Call{Call: _e.mock.On("Get", context1, v, namespace, commitment)}
}

func (_c *MockBlobModule_Get_Call) Run(run func(context1 context.Context, v uint64, namespace share.Namespace, commitment jsonrpc.Commitment)) *MockBlobModule_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 share.Namespace
		if args[2] != nil {
			arg2 = args[2].(share.Namespace)
		}
		var arg3 jsonrpc.Commitment
		if args[3] != nil {
			arg3 = args[3].(jsonrpc.Commitment)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBlobModule_Get_Call) Return(blob *jsonrpc.Blob, err error) *MockBlobModule_Get_Call {
	_c.Call.Return(blob, err)
	return _c
}

func (_c *MockBlobModule_Get_Call) RunAndReturn(run func(context1 context.Context, v uint64, namespace share.Namespace, commitment jsonrpc.Commitment) (*jsonrpc.Blob, error)) *MockBlobModule_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockBlobModule
func (_mock *MockBlobModule) GetAll(context1 context.Context, v uint64, namespaces []share.Namespace) ([]*jsonrpc.Blob, error) {
	ret := _mock.Called(context1, v, namespaces)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*jsonrpc.Blob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, []share.Namespace) ([]*jsonrpc.Blob, error)); ok {
		return returnFunc(context1, v, namespaces)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, []share.Namespace) []*jsonrpc.Blob); ok {
		r0 = returnFunc(context1, v, namespaces)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*jsonrpc.Blob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, []share.Namespace) error); ok {
		r1 = returnFunc(context1, v, namespaces)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobModule_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockBlobModule_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - context1 context.Context
//   - v uint64
//   - namespaces []share.Namespace
func (_e *MockBlobModule_Expecter) GetAll(context1 interface{}, v interface{}, namespaces interface{}) *MockBlobModule_GetAll_Call {
	return &MockBlobModule_GetAll_Call{Call: _e.mock.On("GetAll", context1, v, namespaces)}
}

func (_c *MockBlobModule_GetAll_Call) Run(run func(context1 context.Context, v uint64, namespaces []share.Namespace)) *MockBlobModule_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 []share.Namespace
		if args[2] != nil {
			arg2 = args[2].([]share.Namespace)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBlobModule_GetAll_Call) Return(blobs []*jsonrpc.Blob, err error) *MockBlobModule_GetAll_Call {
	_c.Call.Return(blobs, err)
	return _c
}

func (_c *MockBlobModule_GetAll_Call) RunAndReturn(run func(context1 context.Context, v uint64, namespaces []share.Namespace) ([]*jsonrpc.Blob, error)) *MockBlobModule_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommitmentProof provides a mock function for the type MockBlobModule
func (_mock *MockBlobModule) GetCommitmentProof(context1 context.Context, v uint64, namespace share.Namespace, bytes []byte) (*jsonrpc.CommitmentProof, error) {
	ret := _mock.Called(context1, v, namespace, bytes)

	if len(ret) == 0 {
		panic("no return value specified for GetCommitmentProof")
	}

	var r0 *jsonrpc.CommitmentProof
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, share.Namespace, []byte) (*jsonrpc.CommitmentProof, error)); ok {
		return returnFunc(context1, v, namespace, bytes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, share.Namespace, []byte) *jsonrpc.CommitmentProof); ok {
		r0 = returnFunc(context1, v, namespace, bytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jsonrpc.CommitmentProof)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, share.Namespace, []byte) error); ok {
		r1 = returnFunc(context1, v, namespace, bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobModule_GetCommitmentProof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommitmentProof'
type MockBlobModule_GetCommitmentProof_Call struct {
	*mock.Call
}

// GetCommitmentProof is a helper method to define mock.On call
//   - context1 context.Context
//   - v uint64
//   - namespace share.Namespace
//   - bytes []byte
func (_e *MockBlobModule_Expecter) GetCommitmentProof(context1 interface{}, v interface{}, namespace interface{}, bytes interface{}) *MockBlobModule_GetCommitmentProof_Call {
	return &MockBlobModule_GetCommitmentProof_Call{Call: _e.mock.On("GetCommitmentProof", context1, v, namespace, bytes)}
}

func (_c *MockBlobModule_GetCommitmentProof_Call) Run(run func(context1 context.Context, v uint64, namespace share.Namespace, bytes []byte)) *MockBlobModule_GetCommitmentProof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 share.Namespace
		if args[2] != nil {
			arg2 = args[2].(share.Namespace)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBlobModule_GetCommitmentProof_Call) Return(commitmentProof *jsonrpc.CommitmentProof, err error) *MockBlobModule_GetCommitmentProof_Call {
	_c.Call.Return(commitmentProof, err)
	return _c
}

func (_c *MockBlobModule_GetCommitmentProof_Call) RunAndReturn(run func(context1 context.Context, v uint64, namespace share.Namespace, bytes []byte) (*jsonrpc.CommitmentProof, error)) *MockBlobModule_GetCommitmentProof_Call {
	_c.Call.Return(run)
	return _c
}

// GetProof provides a mock function for the type MockBlobModule
func (_mock *MockBlobModule) GetProof(context1 context.Context, v uint64, namespace share.Namespace, commitment jsonrpc.Commitment) (*jsonrpc.Proof, error) {
	ret := _mock.Called(context1, v, namespace, commitment)

	if len(ret) == 0 {
		panic("no return value specified for GetProof")
	}

	var r0 *jsonrpc.Proof
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, share.Namespace, jsonrpc.Commitment) (*jsonrpc.Proof, error)); ok {
		return returnFunc(context1, v, namespace, commitment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, share.Namespace, jsonrpc.Commitment) *jsonrpc.Proof); ok {
		r0 = returnFunc(context1, v, namespace, commitment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jsonrpc.Proof)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, share.Namespace, jsonrpc.Commitment) error); ok {
		r1 = returnFunc(context1, v, namespace, commitment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobModule_GetProof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProof'
type MockBlobModule_GetProof_Call struct {
	*mock.Call
}

// GetProof is a helper method to define mock.On call
//   - context1 context.Context
//   - v uint64
//   - namespace share.Namespace
//   - commitment jsonrpc.Commitment
func (_e *MockBlobModule_Expecter) GetProof(context1 interface{}, v interface{}, namespace interface{}, commitment interface{}) *MockBlobModule_GetProof_Call {
	return &MockBlobModule_GetProof_Call{Call: _e.mock.On("GetProof", context1, v, namespace, commitment)}
}

func (_c *MockBlobModule_GetProof_Call) Run(run func(context1 context.Context, v uint64, namespace share.Namespace, commitment jsonrpc.Commitment)) *MockBlobModule_GetProof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 share.Namespace
		if args[2] != nil {
			arg2 = args[2].(share.Namespace)
		}
		var arg3 jsonrpc.Commitment
		if args[3] != nil {
			arg3 = args[3].(jsonrpc.Commitment)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBlobModule_GetProof_Call) Return(proof *jsonrpc.Proof, err error) *MockBlobModule_GetProof_Call {
	_c.Call.Return(proof, err)
	return _c
}

func (_c *MockBlobModule_GetProof_Call) RunAndReturn(run func(context1 context.Context, v uint64, namespace share.Namespace, commitment jsonrpc.Commitment) (*jsonrpc.Proof, error)) *MockBlobModule_GetProof_Call {
	_c.Call.Return(run)
	return _c
}

// Included provides a mock function for the type MockBlobModule
func (_mock *MockBlobModule) Included(context1 context.Context, v uint64, namespace share.Namespace, proof *jsonrpc.Proof, commitment jsonrpc.Commitment) (bool, error) {
	ret := _mock.Called(context1, v, namespace, proof, commitment)

	if len(ret) == 0 {
		panic("no return value specified for Included")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, share.Namespace, *jsonrpc.Proof, jsonrpc.Commitment) (bool, error)); ok {
		return returnFunc(context1, v, namespace, proof, commitment)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, share.Namespace, *jsonrpc.Proof, jsonrpc.Commitment) bool); ok {
		r0 = returnFunc(context1, v, namespace, proof, commitment)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, share.Namespace, *jsonrpc.Proof, jsonrpc.Commitment) error); ok {
		r1 = returnFunc(context1, v, namespace, proof, commitment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobModule_Included_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Included'
type MockBlobModule_Included_Call struct {
	*mock.Call
}

// Included is a helper method to define mock.On call
//   - context1 context.Context
//   - v uint64
//   - namespace share.Namespace
//   - proof *jsonrpc.Proof
//   - commitment jsonrpc.Commitment
func (_e *MockBlobModule_Expecter) Included(context1 interface{}, v interface{}, namespace interface{}, proof interface{}, commitment interface{}) *MockBlobModule_Included_Call {
	return &MockBlobModule_Included_Call{Call: _e.mock.On("Included", context1, v, namespace, proof, commitment)}
}

func (_c *MockBlobModule_Included_Call) Run(run func(context1 context.Context, v uint64, namespace share.Namespace, proof *jsonrpc.Proof, commitment jsonrpc.Commitment)) *MockBlobModule_Included_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 share.Namespace
		if args[2] != nil {
			arg2 = args[2].(share.Namespace)
		}
		var arg3 *jsonrpc.Proof
		if args[3] != nil {
			arg3 = args[3].(*jsonrpc.Proof)
		}
		var arg4 jsonrpc.Commitment
		if args[4] != nil {
			arg4 = args[4].(jsonrpc.Commitment)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockBlobModule_Included_Call) Return(b bool, err error) *MockBlobModule_Included_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBlobModule_Included_Call) RunAndReturn(run func(context1 context.Context, v uint64, namespace share.Namespace, proof *jsonrpc.Proof, commitment jsonrpc.Commitment) (bool, error)) *MockBlobModule_Included_Call {
	_c.Call.Return(run)
	return _c
}

// Submit provides a mock function for the type MockBlobModule
func (_mock *MockBlobModule) Submit(context1 context.Context, blobs []*jsonrpc.Blob, submitOptions *jsonrpc.SubmitOptions) (uint64, error) {
	ret := _mock.Called(context1, blobs, submitOptions)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*jsonrpc.Blob, *jsonrpc.SubmitOptions) (uint64, error)); ok {
		return returnFunc(context1, blobs, submitOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*jsonrpc.Blob, *jsonrpc.SubmitOptions) uint64); ok {
		r0 = returnFunc(context1, blobs, submitOptions)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []*jsonrpc.Blob, *jsonrpc.SubmitOptions) error); ok {
		r1 = returnFunc(context1, blobs, submitOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobModule_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type MockBlobModule_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - context1 context.Context
//   - blobs []*jsonrpc.Blob
//   - submitOptions *jsonrpc.SubmitOptions
func (_e *MockBlobModule_Expecter) Submit(context1 interface{}, blobs interface{}, submitOptions interface{}) *MockBlobModule_Submit_Call {
	return &MockBlobModule_Submit_Call{Call: _e.mock.On("Submit", context1, blobs, submitOptions)}
}

func (_c *MockBlobModule_Submit_Call) Run(run func(context1 context.Context, blobs []*jsonrpc.Blob, submitOptions *jsonrpc.SubmitOptions)) *MockBlobModule_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*jsonrpc.Blob
		if args[1] != nil {
			arg1 = args[1].([]*jsonrpc.Blob)
		}
		var arg2 *jsonrpc.SubmitOptions
		if args[2] != nil {
			arg2 = args[2].(*jsonrpc.SubmitOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBlobModule_Submit_Call) Return(v uint64, err error) *MockBlobModule_Submit_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockBlobModule_Submit_Call) RunAndReturn(run func(context1 context.Context, blobs []*jsonrpc.Blob, submitOptions *jsonrpc.SubmitOptions) (uint64, error)) *MockBlobModule_Submit_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockBlobModule
func (_mock *MockBlobModule) Subscribe(context1 context.Context, namespace share.Namespace) (<-chan *jsonrpc.SubscriptionResponse, error) {
	ret := _mock.Called(context1, namespace)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan *jsonrpc.SubscriptionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, share.Namespace) (<-chan *jsonrpc.SubscriptionResponse, error)); ok {
		return returnFunc(context1, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, share.Namespace) <-chan *jsonrpc.SubscriptionResponse); ok {
		r0 = returnFunc(context1, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *jsonrpc.SubscriptionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, share.Namespace) error); ok {
		r1 = returnFunc(context1, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlobModule_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockBlobModule_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - context1 context.Context
//   - namespace share.Namespace
func (_e *MockBlobModule_Expecter) Subscribe(context1 interface{}, namespace interface{}) *MockBlobModule_Subscribe_Call {
	return &MockBlobModule_Subscribe_Call{Call: _e.mock.On("Subscribe", context1, namespace)}
}

func (_c *MockBlobModule_Subscribe_Call) Run(run func(context1 context.Context, namespace share.Namespace)) *MockBlobModule_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 share.Namespace
		if args[1] != nil {
			arg1 = args[1].(share.Namespace)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlobModule_Subscribe_Call) Return(subscriptionResponseCh <-chan *jsonrpc.SubscriptionResponse, err error) *MockBlobModule_Subscribe_Call {
	_c.Call.Return(subscriptionResponseCh, err)
	return _c
}

func (_c *MockBlobModule_Subscribe_Call) RunAndReturn(run func(context1 context.Context, namespace share.Namespace) (<-chan *jsonrpc.SubscriptionResponse, error)) *MockBlobModule_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
