version: "2"
run:
  modules-download-mode: readonly
  timeout: 10m
  tests: true
  build-tags:
    - evm
    - e2e
    - docker
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - durationcheck
    - errname
    - errcheck
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - makezero
    - gosec
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam
        - rangeValCopy
    gosec:
      excludes:
        - G115
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: duplicated-imports
          severity: error
        - name: exported
          arguments:
            - disableStutteringCheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - prealloc
          - noctx
    paths:
      - third_party$
      - builtin$
      - examples$
  disable:
    - containedctx
    - errcheck
    - gocritic
    - nolintlint
    - testifylint
    - thelper
    - tparallel
    - unparam
    - wrapcheck
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/evstack)
        - prefix(github.com/evstack/ev-node)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
