quiet: false
with-expecter: true
disable-version-string: true
issue-845-fix: true
packages:
  github.com/rollkit/rollkit/core/da:
    interfaces:
      DA:
        config:
          outpkg: mocks
        configs:
          - dir: ./da/internal/mocks
            filename: da.go
          - dir: ./test/mocks
            filename: da.go
  github.com/rollkit/rollkit/core/execution:
    interfaces:
      Executor:
        config:
          dir: ./test/mocks
          outpkg: mocks
          filename: execution.go
  github.com/rollkit/rollkit/core/sequencer:
    interfaces:
      Sequencer:
        config:
          dir: ./test/mocks
          outpkg: mocks
          filename: sequencer.go
  github.com/rollkit/rollkit/pkg/store:
    interfaces:
      Store:
        config:
          dir: ./test/mocks
          outpkg: mocks
          filename: store.go
  github.com/rollkit/rollkit/pkg/p2p:
    interfaces:
      P2PRPC:
        config:
          dir: ./test/mocks
          outpkg: mocks
          filename: p2p.go