coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
ignore:
  - "test"
  - "types/pb"
  - "scripts/"
  - "pkg/rpc/example/"
  - "apps"
  - "tools"
  - "execution/evm" # EVM is covered in e2e/integration tests
  - "**/metrics.go"
  - "client" # TODO: add more tests
  - "block/internal/**/*_mock.go"
