// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: execution/evm/v1/state.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecMeta tracks execution state per height for idempotent execution.
// This enables crash recovery and prevents sibling block creation on retries.
type ExecMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block height this execution metadata is for
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// EL parent block hash used for this execution
	ParentHash []byte `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	// Engine API payload ID (optional, set after forkchoiceUpdatedV3)
	PayloadId []byte `protobuf:"bytes,3,opt,name=payload_id,json=payloadId,proto3" json:"payload_id,omitempty"`
	// EL block hash once built (set after getPayloadV4)
	BlockHash []byte `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// State root from the execution payload
	StateRoot []byte `protobuf:"bytes,5,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	// Hash of the transaction list for sanity checks
	TxHash []byte `protobuf:"bytes,6,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// Block timestamp
	Timestamp int64 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Current execution stage: "started", "built", "submitted", "promoted"
	Stage string `protobuf:"bytes,8,opt,name=stage,proto3" json:"stage,omitempty"`
	// Unix timestamp when this metadata was last updated
	UpdatedAtUnix int64 `protobuf:"varint,9,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecMeta) Reset() {
	*x = ExecMeta{}
	mi := &file_execution_evm_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecMeta) ProtoMessage() {}

func (x *ExecMeta) ProtoReflect() protoreflect.Message {
	mi := &file_execution_evm_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecMeta.ProtoReflect.Descriptor instead.
func (*ExecMeta) Descriptor() ([]byte, []int) {
	return file_execution_evm_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *ExecMeta) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ExecMeta) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecMeta) GetPayloadId() []byte {
	if x != nil {
		return x.PayloadId
	}
	return nil
}

func (x *ExecMeta) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ExecMeta) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *ExecMeta) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *ExecMeta) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExecMeta) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ExecMeta) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

var File_execution_evm_v1_state_proto protoreflect.FileDescriptor

const file_execution_evm_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x1cexecution/evm/v1/state.proto\x12\x10execution.evm.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x02\n" +
	"\bExecMeta\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1f\n" +
	"\vparent_hash\x18\x02 \x01(\fR\n" +
	"parentHash\x12\x1d\n" +
	"\n" +
	"payload_id\x18\x03 \x01(\fR\tpayloadId\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x04 \x01(\fR\tblockHash\x12\x1d\n" +
	"\n" +
	"state_root\x18\x05 \x01(\fR\tstateRoot\x12\x17\n" +
	"\atx_hash\x18\x06 \x01(\fR\x06txHash\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05stage\x18\b \x01(\tR\x05stage\x12&\n" +
	"\x0fupdated_at_unix\x18\t \x01(\x03R\rupdatedAtUnixBDZBgithub.com/evstack/ev-node/execution/evm/types/pb/execution/evm/v1b\x06proto3"

var (
	file_execution_evm_v1_state_proto_rawDescOnce sync.Once
	file_execution_evm_v1_state_proto_rawDescData []byte
)

func file_execution_evm_v1_state_proto_rawDescGZIP() []byte {
	file_execution_evm_v1_state_proto_rawDescOnce.Do(func() {
		file_execution_evm_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execution_evm_v1_state_proto_rawDesc), len(file_execution_evm_v1_state_proto_rawDesc)))
	})
	return file_execution_evm_v1_state_proto_rawDescData
}

var file_execution_evm_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_execution_evm_v1_state_proto_goTypes = []any{
	(*ExecMeta)(nil), // 0: execution.evm.v1.ExecMeta
}
var file_execution_evm_v1_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_execution_evm_v1_state_proto_init() }
func file_execution_evm_v1_state_proto_init() {
	if File_execution_evm_v1_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execution_evm_v1_state_proto_rawDesc), len(file_execution_evm_v1_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_execution_evm_v1_state_proto_goTypes,
		DependencyIndexes: file_execution_evm_v1_state_proto_depIdxs,
		MessageInfos:      file_execution_evm_v1_state_proto_msgTypes,
	}.Build()
	File_execution_evm_v1_state_proto = out.File
	file_execution_evm_v1_state_proto_goTypes = nil
	file_execution_evm_v1_state_proto_depIdxs = nil
}
