// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/evstack/ev-node/pkg/da/node"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHeaderModule creates a new instance of MockHeaderModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHeaderModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHeaderModule {
	mock := &MockHeaderModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHeaderModule is an autogenerated mock type for the HeaderModule type
type MockHeaderModule struct {
	mock.Mock
}

type MockHeaderModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHeaderModule) EXPECT() *MockHeaderModule_Expecter {
	return &MockHeaderModule_Expecter{mock: &_m.Mock}
}

// GetByHeight provides a mock function for the type MockHeaderModule
func (_mock *MockHeaderModule) GetByHeight(context1 context.Context, v uint64) (*node.Header, error) {
	ret := _mock.Called(context1, v)

	if len(ret) == 0 {
		panic("no return value specified for GetByHeight")
	}

	var r0 *node.Header
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*node.Header, error)); ok {
		return returnFunc(context1, v)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *node.Header); ok {
		r0 = returnFunc(context1, v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*node.Header)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(context1, v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHeaderModule_GetByHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHeight'
type MockHeaderModule_GetByHeight_Call struct {
	*mock.Call
}

// GetByHeight is a helper method to define mock.On call
//   - context1 context.Context
//   - v uint64
func (_e *MockHeaderModule_Expecter) GetByHeight(context1 interface{}, v interface{}) *MockHeaderModule_GetByHeight_Call {
	return &MockHeaderModule_GetByHeight_Call{Call: _e.mock.On("GetByHeight", context1, v)}
}

func (_c *MockHeaderModule_GetByHeight_Call) Run(run func(context1 context.Context, v uint64)) *MockHeaderModule_GetByHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHeaderModule_GetByHeight_Call) Return(header *node.Header, err error) *MockHeaderModule_GetByHeight_Call {
	_c.Call.Return(header, err)
	return _c
}

func (_c *MockHeaderModule_GetByHeight_Call) RunAndReturn(run func(context1 context.Context, v uint64) (*node.Header, error)) *MockHeaderModule_GetByHeight_Call {
	_c.Call.Return(run)
	return _c
}

// LocalHead provides a mock function for the type MockHeaderModule
func (_mock *MockHeaderModule) LocalHead(context1 context.Context) (*node.Header, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for LocalHead")
	}

	var r0 *node.Header
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*node.Header, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *node.Header); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*node.Header)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHeaderModule_LocalHead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalHead'
type MockHeaderModule_LocalHead_Call struct {
	*mock.Call
}

// LocalHead is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockHeaderModule_Expecter) LocalHead(context1 interface{}) *MockHeaderModule_LocalHead_Call {
	return &MockHeaderModule_LocalHead_Call{Call: _e.mock.On("LocalHead", context1)}
}

func (_c *MockHeaderModule_LocalHead_Call) Run(run func(context1 context.Context)) *MockHeaderModule_LocalHead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHeaderModule_LocalHead_Call) Return(header *node.Header, err error) *MockHeaderModule_LocalHead_Call {
	_c.Call.Return(header, err)
	return _c
}

func (_c *MockHeaderModule_LocalHead_Call) RunAndReturn(run func(context1 context.Context) (*node.Header, error)) *MockHeaderModule_LocalHead_Call {
	_c.Call.Return(run)
	return _c
}

// NetworkHead provides a mock function for the type MockHeaderModule
func (_mock *MockHeaderModule) NetworkHead(context1 context.Context) (*node.Header, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for NetworkHead")
	}

	var r0 *node.Header
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*node.Header, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *node.Header); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*node.Header)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHeaderModule_NetworkHead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetworkHead'
type MockHeaderModule_NetworkHead_Call struct {
	*mock.Call
}

// NetworkHead is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockHeaderModule_Expecter) NetworkHead(context1 interface{}) *MockHeaderModule_NetworkHead_Call {
	return &MockHeaderModule_NetworkHead_Call{Call: _e.mock.On("NetworkHead", context1)}
}

func (_c *MockHeaderModule_NetworkHead_Call) Run(run func(context1 context.Context)) *MockHeaderModule_NetworkHead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHeaderModule_NetworkHead_Call) Return(header *node.Header, err error) *MockHeaderModule_NetworkHead_Call {
	_c.Call.Return(header, err)
	return _c
}

func (_c *MockHeaderModule_NetworkHead_Call) RunAndReturn(run func(context1 context.Context) (*node.Header, error)) *MockHeaderModule_NetworkHead_Call {
	_c.Call.Return(run)
	return _c
}
