version: "3.8"

services:
  reth:
    container_name: reth
    restart: unless-stopped
    image: ghcr.io/paradigmxyz/reth:v1.2.1
    ports:
      - "9001:9001"
      - "30303:30303"
      - "8545:8545"
      - "8551:8551"
    volumes:
      - ./chain:/root/chain:ro
      - ./jwttoken:/root/jwt:ro
      - logs:/root/logs
    entrypoint: /bin/sh -c
    command:
      - |
          reth node \
          --chain /root/chain/genesis.json \
          --metrics 0.0.0.0:9001 \
          --log.file.directory /root/logs \
          --authrpc.addr 0.0.0.0 \
          --authrpc.port 8551 \
          --authrpc.jwtsecret /root/jwt/jwt.hex \
          --http --http.addr 0.0.0.0 --http.port 8545 \
          --http.api "eth,net,web3,txpool" \
          --disable-discovery
    networks:
      - rollkit-network

  local-da:
    image: ghcr.io/rollkit/local-da:v0.1.0
    ports:
      - "7980:7980"
    command: ["-listen-all"]
    networks:
      - rollkit-network

  rollkit-evm-single:
    image: ghcr.io/rollkit/rollkit-evm-single:v0.1.2
    depends_on:
      reth:
        condition: service_started
      local-da:
        condition: service_started
    volumes:
      - evm-single-data:/data
    entrypoint: /usr/bin/entrypoint.sh
    environment:
      - EVM_ENGINE_URL=http://reth:8551
      - EVM_ETH_URL=http://reth:8545
      - EVM_JWT_SECRET=f747494bb0fb338a0d71f5f9fe5b5034c17cc988c229b59fd71e005ee692e9bf
      - EVM_GENESIS_HASH=0x0a962a0d163416829894c89cb604ae422323bcdf02d7ea08b94d68d3e026a380
      - EVM_BLOCK_TIME=1s
      - EVM_SIGNER_PASSPHRASE=secret
      # - ROLLKIT_DA_ADDRESS=<da_address>
      # - ROLLKIT_DA_AUTH_TOKEN=<da_auth_token>
      # - ROLLKIT_DA_NAMESPACE=<da_namespace>
    networks:
      - rollkit-network

volumes:
  logs:
    driver: local
  evm-single-data:

networks:
  rollkit-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
