// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package syncing

import (
	"context"

	"github.com/celestiaorg/go-header"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHeightStore creates a new instance of MockHeightStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHeightStore[H header.Header[H]](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHeightStore[H] {
	mock := &MockHeightStore[H]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHeightStore is an autogenerated mock type for the HeightStore type
type MockHeightStore[H header.Header[H]] struct {
	mock.Mock
}

type MockHeightStore_Expecter[H header.Header[H]] struct {
	mock *mock.Mock
}

func (_m *MockHeightStore[H]) EXPECT() *MockHeightStore_Expecter[H] {
	return &MockHeightStore_Expecter[H]{mock: &_m.Mock}
}

// GetByHeight provides a mock function for the type MockHeightStore
func (_mock *MockHeightStore[H]) GetByHeight(ctx context.Context, height uint64) (H, uint64, error) {
	ret := _mock.Called(ctx, height)

	if len(ret) == 0 {
		panic("no return value specified for GetByHeight")
	}

	var r0 H
	var r1 uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (H, uint64, error)); ok {
		return returnFunc(ctx, height)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) H); ok {
		r0 = returnFunc(ctx, height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(H)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) uint64); ok {
		r1 = returnFunc(ctx, height)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint64) error); ok {
		r2 = returnFunc(ctx, height)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockHeightStore_GetByHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHeight'
type MockHeightStore_GetByHeight_Call[H header.Header[H]] struct {
	*mock.Call
}

// GetByHeight is a helper method to define mock.On call
//   - ctx context.Context
//   - height uint64
func (_e *MockHeightStore_Expecter[H]) GetByHeight(ctx interface{}, height interface{}) *MockHeightStore_GetByHeight_Call[H] {
	return &MockHeightStore_GetByHeight_Call[H]{Call: _e.mock.On("GetByHeight", ctx, height)}
}

func (_c *MockHeightStore_GetByHeight_Call[H]) Run(run func(ctx context.Context, height uint64)) *MockHeightStore_GetByHeight_Call[H] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHeightStore_GetByHeight_Call[H]) Return(v H, v1 uint64, err error) *MockHeightStore_GetByHeight_Call[H] {
	_c.Call.Return(v, v1, err)
	return _c
}

func (_c *MockHeightStore_GetByHeight_Call[H]) RunAndReturn(run func(ctx context.Context, height uint64) (H, uint64, error)) *MockHeightStore_GetByHeight_Call[H] {
	_c.Call.Return(run)
	return _c
}
