// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package syncing

import (
	"context"

	"github.com/evstack/ev-node/block/internal/common"
	mock "github.com/stretchr/testify/mock"
)

// newMockdaRetriever creates a new instance of mockdaRetriever. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdaRetriever(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdaRetriever {
	mock := &mockdaRetriever{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdaRetriever is an autogenerated mock type for the daRetriever type
type mockdaRetriever struct {
	mock.Mock
}

type mockdaRetriever_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdaRetriever) EXPECT() *mockdaRetriever_Expecter {
	return &mockdaRetriever_Expecter{mock: &_m.Mock}
}

// RetrieveFromDA provides a mock function for the type mockdaRetriever
func (_mock *mockdaRetriever) RetrieveFromDA(ctx context.Context, daHeight uint64) ([]common.DAHeightEvent, error) {
	ret := _mock.Called(ctx, daHeight)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveFromDA")
	}

	var r0 []common.DAHeightEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]common.DAHeightEvent, error)); ok {
		return returnFunc(ctx, daHeight)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []common.DAHeightEvent); ok {
		r0 = returnFunc(ctx, daHeight)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.DAHeightEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, daHeight)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdaRetriever_RetrieveFromDA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveFromDA'
type mockdaRetriever_RetrieveFromDA_Call struct {
	*mock.Call
}

// RetrieveFromDA is a helper method to define mock.On call
//   - ctx context.Context
//   - daHeight uint64
func (_e *mockdaRetriever_Expecter) RetrieveFromDA(ctx interface{}, daHeight interface{}) *mockdaRetriever_RetrieveFromDA_Call {
	return &mockdaRetriever_RetrieveFromDA_Call{Call: _e.mock.On("RetrieveFromDA", ctx, daHeight)}
}

func (_c *mockdaRetriever_RetrieveFromDA_Call) Run(run func(ctx context.Context, daHeight uint64)) *mockdaRetriever_RetrieveFromDA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockdaRetriever_RetrieveFromDA_Call) Return(dAHeightEvents []common.DAHeightEvent, err error) *mockdaRetriever_RetrieveFromDA_Call {
	_c.Call.Return(dAHeightEvents, err)
	return _c
}

func (_c *mockdaRetriever_RetrieveFromDA_Call) RunAndReturn(run func(ctx context.Context, daHeight uint64) ([]common.DAHeightEvent, error)) *mockdaRetriever_RetrieveFromDA_Call {
	_c.Call.Return(run)
	return _c
}

// newMockp2pHandler creates a new instance of mockp2pHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockp2pHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockp2pHandler {
	mock := &mockp2pHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockp2pHandler is an autogenerated mock type for the p2pHandler type
type mockp2pHandler struct {
	mock.Mock
}

type mockp2pHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockp2pHandler) EXPECT() *mockp2pHandler_Expecter {
	return &mockp2pHandler_Expecter{mock: &_m.Mock}
}

// ProcessHeight provides a mock function for the type mockp2pHandler
func (_mock *mockp2pHandler) ProcessHeight(ctx context.Context, height uint64, heightInCh chan<- common.DAHeightEvent) error {
	ret := _mock.Called(ctx, height, heightInCh)

	if len(ret) == 0 {
		panic("no return value specified for ProcessHeight")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, chan<- common.DAHeightEvent) error); ok {
		r0 = returnFunc(ctx, height, heightInCh)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockp2pHandler_ProcessHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessHeight'
type mockp2pHandler_ProcessHeight_Call struct {
	*mock.Call
}

// ProcessHeight is a helper method to define mock.On call
//   - ctx context.Context
//   - height uint64
//   - heightInCh chan<- common.DAHeightEvent
func (_e *mockp2pHandler_Expecter) ProcessHeight(ctx interface{}, height interface{}, heightInCh interface{}) *mockp2pHandler_ProcessHeight_Call {
	return &mockp2pHandler_ProcessHeight_Call{Call: _e.mock.On("ProcessHeight", ctx, height, heightInCh)}
}

func (_c *mockp2pHandler_ProcessHeight_Call) Run(run func(ctx context.Context, height uint64, heightInCh chan<- common.DAHeightEvent)) *mockp2pHandler_ProcessHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 chan<- common.DAHeightEvent
		if args[2] != nil {
			arg2 = args[2].(chan<- common.DAHeightEvent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockp2pHandler_ProcessHeight_Call) Return(err error) *mockp2pHandler_ProcessHeight_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockp2pHandler_ProcessHeight_Call) RunAndReturn(run func(ctx context.Context, height uint64, heightInCh chan<- common.DAHeightEvent) error) *mockp2pHandler_ProcessHeight_Call {
	_c.Call.Return(run)
	return _c
}

// SetProcessedHeight provides a mock function for the type mockp2pHandler
func (_mock *mockp2pHandler) SetProcessedHeight(height uint64) {
	_mock.Called(height)
	return
}

// mockp2pHandler_SetProcessedHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetProcessedHeight'
type mockp2pHandler_SetProcessedHeight_Call struct {
	*mock.Call
}

// SetProcessedHeight is a helper method to define mock.On call
//   - height uint64
func (_e *mockp2pHandler_Expecter) SetProcessedHeight(height interface{}) *mockp2pHandler_SetProcessedHeight_Call {
	return &mockp2pHandler_SetProcessedHeight_Call{Call: _e.mock.On("SetProcessedHeight", height)}
}

func (_c *mockp2pHandler_SetProcessedHeight_Call) Run(run func(height uint64)) *mockp2pHandler_SetProcessedHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockp2pHandler_SetProcessedHeight_Call) Return() *mockp2pHandler_SetProcessedHeight_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockp2pHandler_SetProcessedHeight_Call) RunAndReturn(run func(height uint64)) *mockp2pHandler_SetProcessedHeight_Call {
	_c.Run(run)
	return _c
}
