// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/evstack/ev-node/types"
	"github.com/ipfs/go-datastore"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBatch creates a new instance of MockBatch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBatch(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBatch {
	mock := &MockBatch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBatch is an autogenerated mock type for the Batch type
type MockBatch struct {
	mock.Mock
}

type MockBatch_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBatch) EXPECT() *MockBatch_Expecter {
	return &MockBatch_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type MockBatch
func (_mock *MockBatch) Commit() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatch_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockBatch_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *MockBatch_Expecter) Commit() *MockBatch_Commit_Call {
	return &MockBatch_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *MockBatch_Commit_Call) Run(run func()) *MockBatch_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBatch_Commit_Call) Return(err error) *MockBatch_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatch_Commit_Call) RunAndReturn(run func() error) *MockBatch_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockBatch
func (_mock *MockBatch) Delete(key datastore.Key) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(datastore.Key) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatch_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBatch_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - key datastore.Key
func (_e *MockBatch_Expecter) Delete(key interface{}) *MockBatch_Delete_Call {
	return &MockBatch_Delete_Call{Call: _e.mock.On("Delete", key)}
}

func (_c *MockBatch_Delete_Call) Run(run func(key datastore.Key)) *MockBatch_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 datastore.Key
		if args[0] != nil {
			arg0 = args[0].(datastore.Key)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBatch_Delete_Call) Return(err error) *MockBatch_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatch_Delete_Call) RunAndReturn(run func(key datastore.Key) error) *MockBatch_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockBatch
func (_mock *MockBatch) Put(key datastore.Key, value []byte) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(datastore.Key, []byte) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatch_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockBatch_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - key datastore.Key
//   - value []byte
func (_e *MockBatch_Expecter) Put(key interface{}, value interface{}) *MockBatch_Put_Call {
	return &MockBatch_Put_Call{Call: _e.mock.On("Put", key, value)}
}

func (_c *MockBatch_Put_Call) Run(run func(key datastore.Key, value []byte)) *MockBatch_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 datastore.Key
		if args[0] != nil {
			arg0 = args[0].(datastore.Key)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBatch_Put_Call) Return(err error) *MockBatch_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatch_Put_Call) RunAndReturn(run func(key datastore.Key, value []byte) error) *MockBatch_Put_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBlockData provides a mock function for the type MockBatch
func (_mock *MockBatch) SaveBlockData(header *types.SignedHeader, data *types.Data, signature *types.Signature) error {
	ret := _mock.Called(header, data, signature)

	if len(ret) == 0 {
		panic("no return value specified for SaveBlockData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*types.SignedHeader, *types.Data, *types.Signature) error); ok {
		r0 = returnFunc(header, data, signature)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatch_SaveBlockData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBlockData'
type MockBatch_SaveBlockData_Call struct {
	*mock.Call
}

// SaveBlockData is a helper method to define mock.On call
//   - header *types.SignedHeader
//   - data *types.Data
//   - signature *types.Signature
func (_e *MockBatch_Expecter) SaveBlockData(header interface{}, data interface{}, signature interface{}) *MockBatch_SaveBlockData_Call {
	return &MockBatch_SaveBlockData_Call{Call: _e.mock.On("SaveBlockData", header, data, signature)}
}

func (_c *MockBatch_SaveBlockData_Call) Run(run func(header *types.SignedHeader, data *types.Data, signature *types.Signature)) *MockBatch_SaveBlockData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *types.SignedHeader
		if args[0] != nil {
			arg0 = args[0].(*types.SignedHeader)
		}
		var arg1 *types.Data
		if args[1] != nil {
			arg1 = args[1].(*types.Data)
		}
		var arg2 *types.Signature
		if args[2] != nil {
			arg2 = args[2].(*types.Signature)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBatch_SaveBlockData_Call) Return(err error) *MockBatch_SaveBlockData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatch_SaveBlockData_Call) RunAndReturn(run func(header *types.SignedHeader, data *types.Data, signature *types.Signature) error) *MockBatch_SaveBlockData_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeight provides a mock function for the type MockBatch
func (_mock *MockBatch) SetHeight(height uint64) error {
	ret := _mock.Called(height)

	if len(ret) == 0 {
		panic("no return value specified for SetHeight")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(height)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatch_SetHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeight'
type MockBatch_SetHeight_Call struct {
	*mock.Call
}

// SetHeight is a helper method to define mock.On call
//   - height uint64
func (_e *MockBatch_Expecter) SetHeight(height interface{}) *MockBatch_SetHeight_Call {
	return &MockBatch_SetHeight_Call{Call: _e.mock.On("SetHeight", height)}
}

func (_c *MockBatch_SetHeight_Call) Run(run func(height uint64)) *MockBatch_SetHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBatch_SetHeight_Call) Return(err error) *MockBatch_SetHeight_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatch_SetHeight_Call) RunAndReturn(run func(height uint64) error) *MockBatch_SetHeight_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateState provides a mock function for the type MockBatch
func (_mock *MockBatch) UpdateState(state types.State) error {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for UpdateState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(types.State) error); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatch_UpdateState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateState'
type MockBatch_UpdateState_Call struct {
	*mock.Call
}

// UpdateState is a helper method to define mock.On call
//   - state types.State
func (_e *MockBatch_Expecter) UpdateState(state interface{}) *MockBatch_UpdateState_Call {
	return &MockBatch_UpdateState_Call{Call: _e.mock.On("UpdateState", state)}
}

func (_c *MockBatch_UpdateState_Call) Run(run func(state types.State)) *MockBatch_UpdateState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 types.State
		if args[0] != nil {
			arg0 = args[0].(types.State)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBatch_UpdateState_Call) Return(err error) *MockBatch_UpdateState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatch_UpdateState_Call) RunAndReturn(run func(state types.State) error) *MockBatch_UpdateState_Call {
	_c.Call.Return(run)
	return _c
}
