// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/evstack/ev-node/types"
	"github.com/ipfs/go-datastore"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBatch creates a new instance of MockBatch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBatch(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBatch {
	mock := &MockBatch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBatch is an autogenerated mock type for the Batch type
type MockBatch struct {
	mock.Mock
}

type MockBatch_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBatch) EXPECT() *MockBatch_Expecter {
	return &MockBatch_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type MockBatch
func (_mock *MockBatch) Commit(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatch_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockBatch_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBatch_Expecter) Commit(ctx interface{}) *MockBatch_Commit_Call {
	return &MockBatch_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockBatch_Commit_Call) Run(run func(ctx context.Context)) *MockBatch_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBatch_Commit_Call) Return(err error) *MockBatch_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatch_Commit_Call) RunAndReturn(run func(context.Context) error) *MockBatch_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockBatch
func (_mock *MockBatch) Delete(ctx context.Context, key datastore.Key) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, datastore.Key) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatch_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBatch_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key datastore.Key
func (_e *MockBatch_Expecter) Delete(ctx interface{}, key interface{}) *MockBatch_Delete_Call {
	return &MockBatch_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockBatch_Delete_Call) Run(run func(ctx context.Context, key datastore.Key)) *MockBatch_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg1 datastore.Key
		if args[1] != nil {
			arg1 = args[1].(datastore.Key)
		}
		run(args[0].(context.Context), arg1)
	})
	return _c
}

func (_c *MockBatch_Delete_Call) Return(err error) *MockBatch_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatch_Delete_Call) RunAndReturn(run func(context.Context, datastore.Key) error) *MockBatch_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockBatch
func (_mock *MockBatch) Put(ctx context.Context, key datastore.Key, value []byte) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, datastore.Key, []byte) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatch_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockBatch_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key datastore.Key
//   - value []byte
func (_e *MockBatch_Expecter) Put(ctx interface{}, key interface{}, value interface{}) *MockBatch_Put_Call {
	return &MockBatch_Put_Call{Call: _e.mock.On("Put", ctx, key, value)}
}

func (_c *MockBatch_Put_Call) Run(run func(ctx context.Context, key datastore.Key, value []byte)) *MockBatch_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg1 datastore.Key
		if args[1] != nil {
			arg1 = args[1].(datastore.Key)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(args[0].(context.Context), arg1, arg2)
	})
	return _c
}

func (_c *MockBatch_Put_Call) Return(err error) *MockBatch_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatch_Put_Call) RunAndReturn(run func(context.Context, datastore.Key, []byte) error) *MockBatch_Put_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBlockData provides a mock function for the type MockBatch
func (_mock *MockBatch) SaveBlockData(ctx context.Context, header *types.SignedHeader, data *types.Data, signature *types.Signature) error {
	ret := _mock.Called(ctx, header, data, signature)

	if len(ret) == 0 {
		panic("no return value specified for SaveBlockData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.SignedHeader, *types.Data, *types.Signature) error); ok {
		r0 = returnFunc(ctx, header, data, signature)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatch_SaveBlockData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBlockData'
type MockBatch_SaveBlockData_Call struct {
	*mock.Call
}

// SaveBlockData is a helper method to define mock.On call
//   - ctx context.Context
//   - header *types.SignedHeader
//   - data *types.Data
//   - signature *types.Signature
func (_e *MockBatch_Expecter) SaveBlockData(ctx interface{}, header interface{}, data interface{}, signature interface{}) *MockBatch_SaveBlockData_Call {
	return &MockBatch_SaveBlockData_Call{Call: _e.mock.On("SaveBlockData", ctx, header, data, signature)}
}

func (_c *MockBatch_SaveBlockData_Call) Run(run func(ctx context.Context, header *types.SignedHeader, data *types.Data, signature *types.Signature)) *MockBatch_SaveBlockData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg1 *types.SignedHeader
		if args[1] != nil {
			arg1 = args[1].(*types.SignedHeader)
		}
		var arg2 *types.Data
		if args[2] != nil {
			arg2 = args[2].(*types.Data)
		}
		var arg3 *types.Signature
		if args[3] != nil {
			arg3 = args[3].(*types.Signature)
		}
		run(args[0].(context.Context), arg1, arg2, arg3)
	})
	return _c
}

func (_c *MockBatch_SaveBlockData_Call) Return(err error) *MockBatch_SaveBlockData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatch_SaveBlockData_Call) RunAndReturn(run func(context.Context, *types.SignedHeader, *types.Data, *types.Signature) error) *MockBatch_SaveBlockData_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeight provides a mock function for the type MockBatch
func (_mock *MockBatch) SetHeight(ctx context.Context, height uint64) error {
	ret := _mock.Called(ctx, height)

	if len(ret) == 0 {
		panic("no return value specified for SetHeight")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = returnFunc(ctx, height)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatch_SetHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeight'
type MockBatch_SetHeight_Call struct {
	*mock.Call
}

// SetHeight is a helper method to define mock.On call
//   - ctx context.Context
//   - height uint64
func (_e *MockBatch_Expecter) SetHeight(ctx interface{}, height interface{}) *MockBatch_SetHeight_Call {
	return &MockBatch_SetHeight_Call{Call: _e.mock.On("SetHeight", ctx, height)}
}

func (_c *MockBatch_SetHeight_Call) Run(run func(ctx context.Context, height uint64)) *MockBatch_SetHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(args[0].(context.Context), arg1)
	})
	return _c
}

func (_c *MockBatch_SetHeight_Call) Return(err error) *MockBatch_SetHeight_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatch_SetHeight_Call) RunAndReturn(run func(context.Context, uint64) error) *MockBatch_SetHeight_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateState provides a mock function for the type MockBatch
func (_mock *MockBatch) UpdateState(ctx context.Context, state types.State) error {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for UpdateState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.State) error); ok {
		r0 = returnFunc(ctx, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBatch_UpdateState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateState'
type MockBatch_UpdateState_Call struct {
	*mock.Call
}

// UpdateState is a helper method to define mock.On call
//   - ctx context.Context
//   - state types.State
func (_e *MockBatch_Expecter) UpdateState(ctx interface{}, state interface{}) *MockBatch_UpdateState_Call {
	return &MockBatch_UpdateState_Call{Call: _e.mock.On("UpdateState", ctx, state)}
}

func (_c *MockBatch_UpdateState_Call) Run(run func(ctx context.Context, state types.State)) *MockBatch_UpdateState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg1 types.State
		if args[1] != nil {
			arg1 = args[1].(types.State)
		}
		run(args[0].(context.Context), arg1)
	})
	return _c
}

func (_c *MockBatch_UpdateState_Call) Return(err error) *MockBatch_UpdateState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBatch_UpdateState_Call) RunAndReturn(run func(context.Context, types.State) error) *MockBatch_UpdateState_Call {
	_c.Call.Return(run)
	return _c
}
