// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	da "github.com/evstack/ev-node/pkg/da/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockClient
func (_mock *MockClient) Get(ctx context.Context, ids []da.ID, namespace []byte) ([]da.Blob, error) {
	ret := _mock.Called(ctx, ids, namespace)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []da.Blob
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []da.ID, []byte) ([]da.Blob, error)); ok {
		return returnFunc(ctx, ids, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []da.ID, []byte) []da.Blob); ok {
		r0 = returnFunc(ctx, ids, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]da.Blob)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []da.ID, []byte) error); ok {
		r1 = returnFunc(ctx, ids, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []da.ID
//   - namespace []byte
func (_e *MockClient_Expecter) Get(ctx interface{}, ids interface{}, namespace interface{}) *MockClient_Get_Call {
	return &MockClient_Get_Call{Call: _e.mock.On("Get", ctx, ids, namespace)}
}

func (_c *MockClient_Get_Call) Run(run func(ctx context.Context, ids []da.ID, namespace []byte)) *MockClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []da.ID
		if args[1] != nil {
			arg1 = args[1].([]da.ID)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_Get_Call) Return(vs []da.Blob, err error) *MockClient_Get_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockClient_Get_Call) RunAndReturn(run func(ctx context.Context, ids []da.ID, namespace []byte) ([]da.Blob, error)) *MockClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetDataNamespace provides a mock function for the type MockClient
func (_mock *MockClient) GetDataNamespace() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDataNamespace")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockClient_GetDataNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDataNamespace'
type MockClient_GetDataNamespace_Call struct {
	*mock.Call
}

// GetDataNamespace is a helper method to define mock.On call
func (_e *MockClient_Expecter) GetDataNamespace() *MockClient_GetDataNamespace_Call {
	return &MockClient_GetDataNamespace_Call{Call: _e.mock.On("GetDataNamespace")}
}

func (_c *MockClient_GetDataNamespace_Call) Run(run func()) *MockClient_GetDataNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_GetDataNamespace_Call) Return(bytes []byte) *MockClient_GetDataNamespace_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockClient_GetDataNamespace_Call) RunAndReturn(run func() []byte) *MockClient_GetDataNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// GetForcedInclusionNamespace provides a mock function for the type MockClient
func (_mock *MockClient) GetForcedInclusionNamespace() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetForcedInclusionNamespace")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockClient_GetForcedInclusionNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForcedInclusionNamespace'
type MockClient_GetForcedInclusionNamespace_Call struct {
	*mock.Call
}

// GetForcedInclusionNamespace is a helper method to define mock.On call
func (_e *MockClient_Expecter) GetForcedInclusionNamespace() *MockClient_GetForcedInclusionNamespace_Call {
	return &MockClient_GetForcedInclusionNamespace_Call{Call: _e.mock.On("GetForcedInclusionNamespace")}
}

func (_c *MockClient_GetForcedInclusionNamespace_Call) Run(run func()) *MockClient_GetForcedInclusionNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_GetForcedInclusionNamespace_Call) Return(bytes []byte) *MockClient_GetForcedInclusionNamespace_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockClient_GetForcedInclusionNamespace_Call) RunAndReturn(run func() []byte) *MockClient_GetForcedInclusionNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// GetHeaderNamespace provides a mock function for the type MockClient
func (_mock *MockClient) GetHeaderNamespace() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHeaderNamespace")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockClient_GetHeaderNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeaderNamespace'
type MockClient_GetHeaderNamespace_Call struct {
	*mock.Call
}

// GetHeaderNamespace is a helper method to define mock.On call
func (_e *MockClient_Expecter) GetHeaderNamespace() *MockClient_GetHeaderNamespace_Call {
	return &MockClient_GetHeaderNamespace_Call{Call: _e.mock.On("GetHeaderNamespace")}
}

func (_c *MockClient_GetHeaderNamespace_Call) Run(run func()) *MockClient_GetHeaderNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_GetHeaderNamespace_Call) Return(bytes []byte) *MockClient_GetHeaderNamespace_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockClient_GetHeaderNamespace_Call) RunAndReturn(run func() []byte) *MockClient_GetHeaderNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// HasForcedInclusionNamespace provides a mock function for the type MockClient
func (_mock *MockClient) HasForcedInclusionNamespace() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasForcedInclusionNamespace")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockClient_HasForcedInclusionNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasForcedInclusionNamespace'
type MockClient_HasForcedInclusionNamespace_Call struct {
	*mock.Call
}

// HasForcedInclusionNamespace is a helper method to define mock.On call
func (_e *MockClient_Expecter) HasForcedInclusionNamespace() *MockClient_HasForcedInclusionNamespace_Call {
	return &MockClient_HasForcedInclusionNamespace_Call{Call: _e.mock.On("HasForcedInclusionNamespace")}
}

func (_c *MockClient_HasForcedInclusionNamespace_Call) Run(run func()) *MockClient_HasForcedInclusionNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_HasForcedInclusionNamespace_Call) Return(b bool) *MockClient_HasForcedInclusionNamespace_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockClient_HasForcedInclusionNamespace_Call) RunAndReturn(run func() bool) *MockClient_HasForcedInclusionNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// Retrieve provides a mock function for the type MockClient
func (_mock *MockClient) Retrieve(ctx context.Context, height uint64, namespace []byte) da.ResultRetrieve {
	ret := _mock.Called(ctx, height, namespace)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 da.ResultRetrieve
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, []byte) da.ResultRetrieve); ok {
		r0 = returnFunc(ctx, height, namespace)
	} else {
		r0 = ret.Get(0).(da.ResultRetrieve)
	}
	return r0
}

// MockClient_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type MockClient_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ctx context.Context
//   - height uint64
//   - namespace []byte
func (_e *MockClient_Expecter) Retrieve(ctx interface{}, height interface{}, namespace interface{}) *MockClient_Retrieve_Call {
	return &MockClient_Retrieve_Call{Call: _e.mock.On("Retrieve", ctx, height, namespace)}
}

func (_c *MockClient_Retrieve_Call) Run(run func(ctx context.Context, height uint64, namespace []byte)) *MockClient_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_Retrieve_Call) Return(resultRetrieve da.ResultRetrieve) *MockClient_Retrieve_Call {
	_c.Call.Return(resultRetrieve)
	return _c
}

func (_c *MockClient_Retrieve_Call) RunAndReturn(run func(ctx context.Context, height uint64, namespace []byte) da.ResultRetrieve) *MockClient_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// Submit provides a mock function for the type MockClient
func (_mock *MockClient) Submit(ctx context.Context, data [][]byte, gasPrice float64, namespace []byte, options []byte) da.ResultSubmit {
	ret := _mock.Called(ctx, data, gasPrice, namespace, options)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 da.ResultSubmit
	if returnFunc, ok := ret.Get(0).(func(context.Context, [][]byte, float64, []byte, []byte) da.ResultSubmit); ok {
		r0 = returnFunc(ctx, data, gasPrice, namespace, options)
	} else {
		r0 = ret.Get(0).(da.ResultSubmit)
	}
	return r0
}

// MockClient_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type MockClient_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - ctx context.Context
//   - data [][]byte
//   - gasPrice float64
//   - namespace []byte
//   - options []byte
func (_e *MockClient_Expecter) Submit(ctx interface{}, data interface{}, gasPrice interface{}, namespace interface{}, options interface{}) *MockClient_Submit_Call {
	return &MockClient_Submit_Call{Call: _e.mock.On("Submit", ctx, data, gasPrice, namespace, options)}
}

func (_c *MockClient_Submit_Call) Run(run func(ctx context.Context, data [][]byte, gasPrice float64, namespace []byte, options []byte)) *MockClient_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 [][]byte
		if args[1] != nil {
			arg1 = args[1].([][]byte)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		var arg4 []byte
		if args[4] != nil {
			arg4 = args[4].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_Submit_Call) Return(resultSubmit da.ResultSubmit) *MockClient_Submit_Call {
	_c.Call.Return(resultSubmit)
	return _c
}

func (_c *MockClient_Submit_Call) RunAndReturn(run func(ctx context.Context, data [][]byte, gasPrice float64, namespace []byte, options []byte) da.ResultSubmit) *MockClient_Submit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVerifier creates a new instance of MockVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifier {
	mock := &MockVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVerifier is an autogenerated mock type for the Verifier type
type MockVerifier struct {
	mock.Mock
}

type MockVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifier) EXPECT() *MockVerifier_Expecter {
	return &MockVerifier_Expecter{mock: &_m.Mock}
}

// GetProofs provides a mock function for the type MockVerifier
func (_mock *MockVerifier) GetProofs(ctx context.Context, ids []da.ID, namespace []byte) ([]da.Proof, error) {
	ret := _mock.Called(ctx, ids, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetProofs")
	}

	var r0 []da.Proof
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []da.ID, []byte) ([]da.Proof, error)); ok {
		return returnFunc(ctx, ids, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []da.ID, []byte) []da.Proof); ok {
		r0 = returnFunc(ctx, ids, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]da.Proof)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []da.ID, []byte) error); ok {
		r1 = returnFunc(ctx, ids, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerifier_GetProofs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProofs'
type MockVerifier_GetProofs_Call struct {
	*mock.Call
}

// GetProofs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []da.ID
//   - namespace []byte
func (_e *MockVerifier_Expecter) GetProofs(ctx interface{}, ids interface{}, namespace interface{}) *MockVerifier_GetProofs_Call {
	return &MockVerifier_GetProofs_Call{Call: _e.mock.On("GetProofs", ctx, ids, namespace)}
}

func (_c *MockVerifier_GetProofs_Call) Run(run func(ctx context.Context, ids []da.ID, namespace []byte)) *MockVerifier_GetProofs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []da.ID
		if args[1] != nil {
			arg1 = args[1].([]da.ID)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVerifier_GetProofs_Call) Return(vs []da.Proof, err error) *MockVerifier_GetProofs_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockVerifier_GetProofs_Call) RunAndReturn(run func(ctx context.Context, ids []da.ID, namespace []byte) ([]da.Proof, error)) *MockVerifier_GetProofs_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockVerifier
func (_mock *MockVerifier) Validate(ctx context.Context, ids []da.ID, proofs []da.Proof, namespace []byte) ([]bool, error) {
	ret := _mock.Called(ctx, ids, proofs, namespace)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 []bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []da.ID, []da.Proof, []byte) ([]bool, error)); ok {
		return returnFunc(ctx, ids, proofs, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []da.ID, []da.Proof, []byte) []bool); ok {
		r0 = returnFunc(ctx, ids, proofs, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []da.ID, []da.Proof, []byte) error); ok {
		r1 = returnFunc(ctx, ids, proofs, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerifier_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockVerifier_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []da.ID
//   - proofs []da.Proof
//   - namespace []byte
func (_e *MockVerifier_Expecter) Validate(ctx interface{}, ids interface{}, proofs interface{}, namespace interface{}) *MockVerifier_Validate_Call {
	return &MockVerifier_Validate_Call{Call: _e.mock.On("Validate", ctx, ids, proofs, namespace)}
}

func (_c *MockVerifier_Validate_Call) Run(run func(ctx context.Context, ids []da.ID, proofs []da.Proof, namespace []byte)) *MockVerifier_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []da.ID
		if args[1] != nil {
			arg1 = args[1].([]da.ID)
		}
		var arg2 []da.Proof
		if args[2] != nil {
			arg2 = args[2].([]da.Proof)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockVerifier_Validate_Call) Return(bools []bool, err error) *MockVerifier_Validate_Call {
	_c.Call.Return(bools, err)
	return _c
}

func (_c *MockVerifier_Validate_Call) RunAndReturn(run func(ctx context.Context, ids []da.ID, proofs []da.Proof, namespace []byte) ([]bool, error)) *MockVerifier_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockClient
func (_mock *MockClient) Subscribe(ctx context.Context, namespace []byte) (<-chan da.ResultRetrieve, error) {
	ret := _mock.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan da.ResultRetrieve
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) (<-chan da.ResultRetrieve, error)); ok {
		return returnFunc(ctx, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) <-chan da.ResultRetrieve); ok {
		r0 = returnFunc(ctx, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan da.ResultRetrieve)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockClient_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace []byte
func (_e *MockClient_Expecter) Subscribe(ctx interface{}, namespace interface{}) *MockClient_Subscribe_Call {
	return &MockClient_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, namespace)}
}

func (_c *MockClient_Subscribe_Call) Run(run func(ctx context.Context, namespace []byte)) *MockClient_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Subscribe_Call) Return(outCh <-chan da.ResultRetrieve, err error) *MockClient_Subscribe_Call {
	_c.Call.Return(outCh, err)
	return _c
}

func (_c *MockClient_Subscribe_Call) RunAndReturn(run func(ctx context.Context, namespace []byte) (<-chan da.ResultRetrieve, error)) *MockClient_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
