// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/evstack/ev-node/pkg/da/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVerifier creates a new instance of MockVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVerifier {
	mock := &MockVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVerifier is an autogenerated mock type for the Verifier type
type MockVerifier struct {
	mock.Mock
}

type MockVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVerifier) EXPECT() *MockVerifier_Expecter {
	return &MockVerifier_Expecter{mock: &_m.Mock}
}

// GetProofs provides a mock function for the type MockVerifier
func (_mock *MockVerifier) GetProofs(ctx context.Context, ids []da.ID, namespace []byte) ([]da.Proof, error) {
	ret := _mock.Called(ctx, ids, namespace)

	if len(ret) == 0 {
		panic("no return value specified for GetProofs")
	}

	var r0 []da.Proof
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []da.ID, []byte) ([]da.Proof, error)); ok {
		return returnFunc(ctx, ids, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []da.ID, []byte) []da.Proof); ok {
		r0 = returnFunc(ctx, ids, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]da.Proof)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []da.ID, []byte) error); ok {
		r1 = returnFunc(ctx, ids, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerifier_GetProofs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProofs'
type MockVerifier_GetProofs_Call struct {
	*mock.Call
}

// GetProofs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []da.ID
//   - namespace []byte
func (_e *MockVerifier_Expecter) GetProofs(ctx interface{}, ids interface{}, namespace interface{}) *MockVerifier_GetProofs_Call {
	return &MockVerifier_GetProofs_Call{Call: _e.mock.On("GetProofs", ctx, ids, namespace)}
}

func (_c *MockVerifier_GetProofs_Call) Run(run func(ctx context.Context, ids []da.ID, namespace []byte)) *MockVerifier_GetProofs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []da.ID
		if args[1] != nil {
			arg1 = args[1].([]da.ID)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVerifier_GetProofs_Call) Return(vs []da.Proof, err error) *MockVerifier_GetProofs_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockVerifier_GetProofs_Call) RunAndReturn(run func(ctx context.Context, ids []da.ID, namespace []byte) ([]da.Proof, error)) *MockVerifier_GetProofs_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockVerifier
func (_mock *MockVerifier) Validate(ctx context.Context, ids []da.ID, proofs []da.Proof, namespace []byte) ([]bool, error) {
	ret := _mock.Called(ctx, ids, proofs, namespace)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 []bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []da.ID, []da.Proof, []byte) ([]bool, error)); ok {
		return returnFunc(ctx, ids, proofs, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []da.ID, []da.Proof, []byte) []bool); ok {
		r0 = returnFunc(ctx, ids, proofs, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []da.ID, []da.Proof, []byte) error); ok {
		r1 = returnFunc(ctx, ids, proofs, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVerifier_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockVerifier_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []da.ID
//   - proofs []da.Proof
//   - namespace []byte
func (_e *MockVerifier_Expecter) Validate(ctx interface{}, ids interface{}, proofs interface{}, namespace interface{}) *MockVerifier_Validate_Call {
	return &MockVerifier_Validate_Call{Call: _e.mock.On("Validate", ctx, ids, proofs, namespace)}
}

func (_c *MockVerifier_Validate_Call) Run(run func(ctx context.Context, ids []da.ID, proofs []da.Proof, namespace []byte)) *MockVerifier_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []da.ID
		if args[1] != nil {
			arg1 = args[1].([]da.ID)
		}
		var arg2 []da.Proof
		if args[2] != nil {
			arg2 = args[2].([]da.Proof)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockVerifier_Validate_Call) Return(bools []bool, err error) *MockVerifier_Validate_Call {
	_c.Call.Return(bools, err)
	return _c
}

func (_c *MockVerifier_Validate_Call) RunAndReturn(run func(ctx context.Context, ids []da.ID, proofs []da.Proof, namespace []byte) ([]bool, error)) *MockVerifier_Validate_Call {
	_c.Call.Return(run)
	return _c
}
