// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package common

import (
	"context"

	"github.com/evstack/ev-node/block"
	mock "github.com/stretchr/testify/mock"
)

// NewMockForcedInclusionRetriever creates a new instance of MockForcedInclusionRetriever. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockForcedInclusionRetriever(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockForcedInclusionRetriever {
	mock := &MockForcedInclusionRetriever{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockForcedInclusionRetriever is an autogenerated mock type for the ForcedInclusionRetriever type
type MockForcedInclusionRetriever struct {
	mock.Mock
}

type MockForcedInclusionRetriever_Expecter struct {
	mock *mock.Mock
}

func (_m *MockForcedInclusionRetriever) EXPECT() *MockForcedInclusionRetriever_Expecter {
	return &MockForcedInclusionRetriever_Expecter{mock: &_m.Mock}
}

// RetrieveForcedIncludedTxs provides a mock function for the type MockForcedInclusionRetriever
func (_mock *MockForcedInclusionRetriever) RetrieveForcedIncludedTxs(ctx context.Context, daHeight uint64) (*block.ForcedInclusionEvent, error) {
	ret := _mock.Called(ctx, daHeight)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveForcedIncludedTxs")
	}

	var r0 *block.ForcedInclusionEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*block.ForcedInclusionEvent, error)); ok {
		return returnFunc(ctx, daHeight)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *block.ForcedInclusionEvent); ok {
		r0 = returnFunc(ctx, daHeight)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*block.ForcedInclusionEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, daHeight)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockForcedInclusionRetriever_RetrieveForcedIncludedTxs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveForcedIncludedTxs'
type MockForcedInclusionRetriever_RetrieveForcedIncludedTxs_Call struct {
	*mock.Call
}

// RetrieveForcedIncludedTxs is a helper method to define mock.On call
//   - ctx context.Context
//   - daHeight uint64
func (_e *MockForcedInclusionRetriever_Expecter) RetrieveForcedIncludedTxs(ctx interface{}, daHeight interface{}) *MockForcedInclusionRetriever_RetrieveForcedIncludedTxs_Call {
	return &MockForcedInclusionRetriever_RetrieveForcedIncludedTxs_Call{Call: _e.mock.On("RetrieveForcedIncludedTxs", ctx, daHeight)}
}

func (_c *MockForcedInclusionRetriever_RetrieveForcedIncludedTxs_Call) Run(run func(ctx context.Context, daHeight uint64)) *MockForcedInclusionRetriever_RetrieveForcedIncludedTxs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockForcedInclusionRetriever_RetrieveForcedIncludedTxs_Call) Return(v *block.ForcedInclusionEvent, err error) *MockForcedInclusionRetriever_RetrieveForcedIncludedTxs_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockForcedInclusionRetriever_RetrieveForcedIncludedTxs_Call) RunAndReturn(run func(ctx context.Context, daHeight uint64) (*block.ForcedInclusionEvent, error)) *MockForcedInclusionRetriever_RetrieveForcedIncludedTxs_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockForcedInclusionRetriever
func (_mock *MockForcedInclusionRetriever) Stop() {
	_mock.Called()
	return
}

// MockForcedInclusionRetriever_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockForcedInclusionRetriever_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockForcedInclusionRetriever_Expecter) Stop() *MockForcedInclusionRetriever_Stop_Call {
	return &MockForcedInclusionRetriever_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockForcedInclusionRetriever_Stop_Call) Run(run func()) *MockForcedInclusionRetriever_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockForcedInclusionRetriever_Stop_Call) Return() *MockForcedInclusionRetriever_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockForcedInclusionRetriever_Stop_Call) RunAndReturn(run func()) *MockForcedInclusionRetriever_Stop_Call {
	_c.Run(run)
	return _c
}
