// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: evnode/v1/da.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlockData contains data retrieved from a single DA height.
type BlockData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in seconds
	Blobs         [][]byte               `protobuf:"bytes,3,rep,name=blobs,proto3" json:"blobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockData) Reset() {
	*x = BlockData{}
	mi := &file_evnode_v1_da_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockData) ProtoMessage() {}

func (x *BlockData) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_da_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockData.ProtoReflect.Descriptor instead.
func (*BlockData) Descriptor() ([]byte, []int) {
	return file_evnode_v1_da_proto_rawDescGZIP(), []int{0}
}

func (x *BlockData) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockData) GetBlobs() [][]byte {
	if x != nil {
		return x.Blobs
	}
	return nil
}

var File_evnode_v1_da_proto protoreflect.FileDescriptor

const file_evnode_v1_da_proto_rawDesc = "" +
	"\n" +
	"\x12evnode/v1/da.proto\x12\tevnode.v1\"W\n" +
	"\tBlockData\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05blobs\x18\x03 \x03(\fR\x05blobsB/Z-github.com/evstack/ev-node/types/pb/evnode/v1b\x06proto3"

var (
	file_evnode_v1_da_proto_rawDescOnce sync.Once
	file_evnode_v1_da_proto_rawDescData []byte
)

func file_evnode_v1_da_proto_rawDescGZIP() []byte {
	file_evnode_v1_da_proto_rawDescOnce.Do(func() {
		file_evnode_v1_da_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evnode_v1_da_proto_rawDesc), len(file_evnode_v1_da_proto_rawDesc)))
	})
	return file_evnode_v1_da_proto_rawDescData
}

var file_evnode_v1_da_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_evnode_v1_da_proto_goTypes = []any{
	(*BlockData)(nil), // 0: evnode.v1.BlockData
}
var file_evnode_v1_da_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_evnode_v1_da_proto_init() }
func file_evnode_v1_da_proto_init() {
	if File_evnode_v1_da_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evnode_v1_da_proto_rawDesc), len(file_evnode_v1_da_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_evnode_v1_da_proto_goTypes,
		DependencyIndexes: file_evnode_v1_da_proto_depIdxs,
		MessageInfos:      file_evnode_v1_da_proto_msgTypes,
	}.Build()
	File_evnode_v1_da_proto = out.File
	file_evnode_v1_da_proto_goTypes = nil
	file_evnode_v1_da_proto_depIdxs = nil
}
