// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: evnode/v1/execution.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FilterStatus represents the result of filtering a transaction
type FilterStatus int32

const (
	// Transaction will make it to the next batch
	FilterStatus_FILTER_OK FilterStatus = 0
	// Transaction will be filtered out because invalid (too big, malformed, etc.)
	FilterStatus_FILTER_REMOVE FilterStatus = 1
	// Transaction is valid but postponed for later processing due to size/gas constraint
	FilterStatus_FILTER_POSTPONE FilterStatus = 2
)

// Enum value maps for FilterStatus.
var (
	FilterStatus_name = map[int32]string{
		0: "FILTER_OK",
		1: "FILTER_REMOVE",
		2: "FILTER_POSTPONE",
	}
	FilterStatus_value = map[string]int32{
		"FILTER_OK":       0,
		"FILTER_REMOVE":   1,
		"FILTER_POSTPONE": 2,
	}
)

func (x FilterStatus) Enum() *FilterStatus {
	p := new(FilterStatus)
	*p = x
	return p
}

func (x FilterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_evnode_v1_execution_proto_enumTypes[0].Descriptor()
}

func (FilterStatus) Type() protoreflect.EnumType {
	return &file_evnode_v1_execution_proto_enumTypes[0]
}

func (x FilterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterStatus.Descriptor instead.
func (FilterStatus) EnumDescriptor() ([]byte, []int) {
	return file_evnode_v1_execution_proto_rawDescGZIP(), []int{0}
}

// InitChainRequest contains the genesis parameters for chain initialization
type InitChainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp marking chain start time in UTC
	GenesisTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=genesis_time,json=genesisTime,proto3" json:"genesis_time,omitempty"`
	// First block height (must be > 0)
	InitialHeight uint64 `protobuf:"varint,2,opt,name=initial_height,json=initialHeight,proto3" json:"initial_height,omitempty"`
	// Unique identifier string for the blockchain
	ChainId       string `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitChainRequest) Reset() {
	*x = InitChainRequest{}
	mi := &file_evnode_v1_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitChainRequest) ProtoMessage() {}

func (x *InitChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitChainRequest.ProtoReflect.Descriptor instead.
func (*InitChainRequest) Descriptor() ([]byte, []int) {
	return file_evnode_v1_execution_proto_rawDescGZIP(), []int{0}
}

func (x *InitChainRequest) GetGenesisTime() *timestamppb.Timestamp {
	if x != nil {
		return x.GenesisTime
	}
	return nil
}

func (x *InitChainRequest) GetInitialHeight() uint64 {
	if x != nil {
		return x.InitialHeight
	}
	return 0
}

func (x *InitChainRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

// InitChainResponse contains the initial state and configuration
type InitChainResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hash representing initial state
	StateRoot     []byte `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitChainResponse) Reset() {
	*x = InitChainResponse{}
	mi := &file_evnode_v1_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitChainResponse) ProtoMessage() {}

func (x *InitChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitChainResponse.ProtoReflect.Descriptor instead.
func (*InitChainResponse) Descriptor() ([]byte, []int) {
	return file_evnode_v1_execution_proto_rawDescGZIP(), []int{1}
}

func (x *InitChainResponse) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

// GetTxsRequest is the request for fetching transactions
type GetTxsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTxsRequest) Reset() {
	*x = GetTxsRequest{}
	mi := &file_evnode_v1_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTxsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxsRequest) ProtoMessage() {}

func (x *GetTxsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxsRequest.ProtoReflect.Descriptor instead.
func (*GetTxsRequest) Descriptor() ([]byte, []int) {
	return file_evnode_v1_execution_proto_rawDescGZIP(), []int{2}
}

// GetTxsResponse contains the available transactions
type GetTxsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Slice of valid transactions from mempool
	Txs           [][]byte `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTxsResponse) Reset() {
	*x = GetTxsResponse{}
	mi := &file_evnode_v1_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTxsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxsResponse) ProtoMessage() {}

func (x *GetTxsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxsResponse.ProtoReflect.Descriptor instead.
func (*GetTxsResponse) Descriptor() ([]byte, []int) {
	return file_evnode_v1_execution_proto_rawDescGZIP(), []int{3}
}

func (x *GetTxsResponse) GetTxs() [][]byte {
	if x != nil {
		return x.Txs
	}
	return nil
}

// ExecuteTxsRequest contains transactions and block context for execution
type ExecuteTxsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered list of transactions to execute
	Txs [][]byte `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	// Height of block being created (must be > 0)
	BlockHeight uint64 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// Block creation time in UTC
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Previous block's state root hash
	PrevStateRoot []byte `protobuf:"bytes,4,opt,name=prev_state_root,json=prevStateRoot,proto3" json:"prev_state_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTxsRequest) Reset() {
	*x = ExecuteTxsRequest{}
	mi := &file_evnode_v1_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTxsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTxsRequest) ProtoMessage() {}

func (x *ExecuteTxsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTxsRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTxsRequest) Descriptor() ([]byte, []int) {
	return file_evnode_v1_execution_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteTxsRequest) GetTxs() [][]byte {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *ExecuteTxsRequest) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *ExecuteTxsRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExecuteTxsRequest) GetPrevStateRoot() []byte {
	if x != nil {
		return x.PrevStateRoot
	}
	return nil
}

// ExecuteTxsResponse contains the result of transaction execution
type ExecuteTxsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New state root after executing transactions
	UpdatedStateRoot []byte `protobuf:"bytes,1,opt,name=updated_state_root,json=updatedStateRoot,proto3" json:"updated_state_root,omitempty"`
	// Maximum allowed transaction size (may change with protocol updates)
	MaxBytes      uint64 `protobuf:"varint,2,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTxsResponse) Reset() {
	*x = ExecuteTxsResponse{}
	mi := &file_evnode_v1_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTxsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTxsResponse) ProtoMessage() {}

func (x *ExecuteTxsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTxsResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTxsResponse) Descriptor() ([]byte, []int) {
	return file_evnode_v1_execution_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteTxsResponse) GetUpdatedStateRoot() []byte {
	if x != nil {
		return x.UpdatedStateRoot
	}
	return nil
}

func (x *ExecuteTxsResponse) GetMaxBytes() uint64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

// SetFinalRequest marks a block as finalized
type SetFinalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Height of block to finalize
	BlockHeight   uint64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFinalRequest) Reset() {
	*x = SetFinalRequest{}
	mi := &file_evnode_v1_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFinalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFinalRequest) ProtoMessage() {}

func (x *SetFinalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFinalRequest.ProtoReflect.Descriptor instead.
func (*SetFinalRequest) Descriptor() ([]byte, []int) {
	return file_evnode_v1_execution_proto_rawDescGZIP(), []int{6}
}

func (x *SetFinalRequest) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

// SetFinalResponse indicates whether finalization was successful
type SetFinalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFinalResponse) Reset() {
	*x = SetFinalResponse{}
	mi := &file_evnode_v1_execution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFinalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFinalResponse) ProtoMessage() {}

func (x *SetFinalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_execution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFinalResponse.ProtoReflect.Descriptor instead.
func (*SetFinalResponse) Descriptor() ([]byte, []int) {
	return file_evnode_v1_execution_proto_rawDescGZIP(), []int{7}
}

// GetExecutionInfoRequest requests execution layer parameters
type GetExecutionInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionInfoRequest) Reset() {
	*x = GetExecutionInfoRequest{}
	mi := &file_evnode_v1_execution_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionInfoRequest) ProtoMessage() {}

func (x *GetExecutionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_execution_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionInfoRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionInfoRequest) Descriptor() ([]byte, []int) {
	return file_evnode_v1_execution_proto_rawDescGZIP(), []int{8}
}

// GetExecutionInfoResponse contains execution layer parameters
type GetExecutionInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum gas allowed for transactions in a block
	// For non-gas-based execution layers, this should be 0
	MaxGas        uint64 `protobuf:"varint,1,opt,name=max_gas,json=maxGas,proto3" json:"max_gas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionInfoResponse) Reset() {
	*x = GetExecutionInfoResponse{}
	mi := &file_evnode_v1_execution_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionInfoResponse) ProtoMessage() {}

func (x *GetExecutionInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_execution_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionInfoResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionInfoResponse) Descriptor() ([]byte, []int) {
	return file_evnode_v1_execution_proto_rawDescGZIP(), []int{9}
}

func (x *GetExecutionInfoResponse) GetMaxGas() uint64 {
	if x != nil {
		return x.MaxGas
	}
	return 0
}

// FilterTxsRequest contains transactions to validate and filter
type FilterTxsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All transactions (force-included + mempool)
	Txs [][]byte `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	// Maximum cumulative size allowed (0 means no size limit)
	MaxBytes uint64 `protobuf:"varint,2,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	// Maximum cumulative gas allowed (0 means no gas limit)
	MaxGas uint64 `protobuf:"varint,3,opt,name=max_gas,json=maxGas,proto3" json:"max_gas,omitempty"`
	// Whether force-included transactions are present
	HasForceIncludedTransaction bool `protobuf:"varint,4,opt,name=has_force_included_transaction,json=hasForceIncludedTransaction,proto3" json:"has_force_included_transaction,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *FilterTxsRequest) Reset() {
	*x = FilterTxsRequest{}
	mi := &file_evnode_v1_execution_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterTxsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterTxsRequest) ProtoMessage() {}

func (x *FilterTxsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_execution_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterTxsRequest.ProtoReflect.Descriptor instead.
func (*FilterTxsRequest) Descriptor() ([]byte, []int) {
	return file_evnode_v1_execution_proto_rawDescGZIP(), []int{10}
}

func (x *FilterTxsRequest) GetTxs() [][]byte {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *FilterTxsRequest) GetMaxBytes() uint64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *FilterTxsRequest) GetMaxGas() uint64 {
	if x != nil {
		return x.MaxGas
	}
	return 0
}

func (x *FilterTxsRequest) GetHasForceIncludedTransaction() bool {
	if x != nil {
		return x.HasForceIncludedTransaction
	}
	return false
}

// FilterTxsResponse contains the filter status for each transaction
type FilterTxsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter status for each transaction (same length as txs in request)
	Statuses      []FilterStatus `protobuf:"varint,1,rep,packed,name=statuses,proto3,enum=evnode.v1.FilterStatus" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterTxsResponse) Reset() {
	*x = FilterTxsResponse{}
	mi := &file_evnode_v1_execution_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterTxsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterTxsResponse) ProtoMessage() {}

func (x *FilterTxsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_execution_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterTxsResponse.ProtoReflect.Descriptor instead.
func (*FilterTxsResponse) Descriptor() ([]byte, []int) {
	return file_evnode_v1_execution_proto_rawDescGZIP(), []int{11}
}

func (x *FilterTxsResponse) GetStatuses() []FilterStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

var File_evnode_v1_execution_proto protoreflect.FileDescriptor

const file_evnode_v1_execution_proto_rawDesc = "" +
	"\n" +
	"\x19evnode/v1/execution.proto\x12\tevnode.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x01\n" +
	"\x10InitChainRequest\x12=\n" +
	"\fgenesis_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vgenesisTime\x12%\n" +
	"\x0einitial_height\x18\x02 \x01(\x04R\rinitialHeight\x12\x19\n" +
	"\bchain_id\x18\x03 \x01(\tR\achainId\"2\n" +
	"\x11InitChainResponse\x12\x1d\n" +
	"\n" +
	"state_root\x18\x01 \x01(\fR\tstateRoot\"\x0f\n" +
	"\rGetTxsRequest\"\"\n" +
	"\x0eGetTxsResponse\x12\x10\n" +
	"\x03txs\x18\x01 \x03(\fR\x03txs\"\xaa\x01\n" +
	"\x11ExecuteTxsRequest\x12\x10\n" +
	"\x03txs\x18\x01 \x03(\fR\x03txs\x12!\n" +
	"\fblock_height\x18\x02 \x01(\x04R\vblockHeight\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12&\n" +
	"\x0fprev_state_root\x18\x04 \x01(\fR\rprevStateRoot\"_\n" +
	"\x12ExecuteTxsResponse\x12,\n" +
	"\x12updated_state_root\x18\x01 \x01(\fR\x10updatedStateRoot\x12\x1b\n" +
	"\tmax_bytes\x18\x02 \x01(\x04R\bmaxBytes\"4\n" +
	"\x0fSetFinalRequest\x12!\n" +
	"\fblock_height\x18\x01 \x01(\x04R\vblockHeight\"\x12\n" +
	"\x10SetFinalResponse\"\x19\n" +
	"\x17GetExecutionInfoRequest\"3\n" +
	"\x18GetExecutionInfoResponse\x12\x17\n" +
	"\amax_gas\x18\x01 \x01(\x04R\x06maxGas\"\x9f\x01\n" +
	"\x10FilterTxsRequest\x12\x10\n" +
	"\x03txs\x18\x01 \x03(\fR\x03txs\x12\x1b\n" +
	"\tmax_bytes\x18\x02 \x01(\x04R\bmaxBytes\x12\x17\n" +
	"\amax_gas\x18\x03 \x01(\x04R\x06maxGas\x12C\n" +
	"\x1ehas_force_included_transaction\x18\x04 \x01(\bR\x1bhasForceIncludedTransaction\"H\n" +
	"\x11FilterTxsResponse\x123\n" +
	"\bstatuses\x18\x01 \x03(\x0e2\x17.evnode.v1.FilterStatusR\bstatuses*E\n" +
	"\fFilterStatus\x12\r\n" +
	"\tFILTER_OK\x10\x00\x12\x11\n" +
	"\rFILTER_REMOVE\x10\x01\x12\x13\n" +
	"\x0fFILTER_POSTPONE\x10\x022\xd9\x03\n" +
	"\x0fExecutorService\x12H\n" +
	"\tInitChain\x12\x1b.evnode.v1.InitChainRequest\x1a\x1c.evnode.v1.InitChainResponse\"\x00\x12?\n" +
	"\x06GetTxs\x12\x18.evnode.v1.GetTxsRequest\x1a\x19.evnode.v1.GetTxsResponse\"\x00\x12K\n" +
	"\n" +
	"ExecuteTxs\x12\x1c.evnode.v1.ExecuteTxsRequest\x1a\x1d.evnode.v1.ExecuteTxsResponse\"\x00\x12E\n" +
	"\bSetFinal\x12\x1a.evnode.v1.SetFinalRequest\x1a\x1b.evnode.v1.SetFinalResponse\"\x00\x12]\n" +
	"\x10GetExecutionInfo\x12\".evnode.v1.GetExecutionInfoRequest\x1a#.evnode.v1.GetExecutionInfoResponse\"\x00\x12H\n" +
	"\tFilterTxs\x12\x1b.evnode.v1.FilterTxsRequest\x1a\x1c.evnode.v1.FilterTxsResponse\"\x00B/Z-github.com/evstack/ev-node/types/pb/evnode/v1b\x06proto3"

var (
	file_evnode_v1_execution_proto_rawDescOnce sync.Once
	file_evnode_v1_execution_proto_rawDescData []byte
)

func file_evnode_v1_execution_proto_rawDescGZIP() []byte {
	file_evnode_v1_execution_proto_rawDescOnce.Do(func() {
		file_evnode_v1_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evnode_v1_execution_proto_rawDesc), len(file_evnode_v1_execution_proto_rawDesc)))
	})
	return file_evnode_v1_execution_proto_rawDescData
}

var file_evnode_v1_execution_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_evnode_v1_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_evnode_v1_execution_proto_goTypes = []any{
	(FilterStatus)(0),                // 0: evnode.v1.FilterStatus
	(*InitChainRequest)(nil),         // 1: evnode.v1.InitChainRequest
	(*InitChainResponse)(nil),        // 2: evnode.v1.InitChainResponse
	(*GetTxsRequest)(nil),            // 3: evnode.v1.GetTxsRequest
	(*GetTxsResponse)(nil),           // 4: evnode.v1.GetTxsResponse
	(*ExecuteTxsRequest)(nil),        // 5: evnode.v1.ExecuteTxsRequest
	(*ExecuteTxsResponse)(nil),       // 6: evnode.v1.ExecuteTxsResponse
	(*SetFinalRequest)(nil),          // 7: evnode.v1.SetFinalRequest
	(*SetFinalResponse)(nil),         // 8: evnode.v1.SetFinalResponse
	(*GetExecutionInfoRequest)(nil),  // 9: evnode.v1.GetExecutionInfoRequest
	(*GetExecutionInfoResponse)(nil), // 10: evnode.v1.GetExecutionInfoResponse
	(*FilterTxsRequest)(nil),         // 11: evnode.v1.FilterTxsRequest
	(*FilterTxsResponse)(nil),        // 12: evnode.v1.FilterTxsResponse
	(*timestamppb.Timestamp)(nil),    // 13: google.protobuf.Timestamp
}
var file_evnode_v1_execution_proto_depIdxs = []int32{
	13, // 0: evnode.v1.InitChainRequest.genesis_time:type_name -> google.protobuf.Timestamp
	13, // 1: evnode.v1.ExecuteTxsRequest.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 2: evnode.v1.FilterTxsResponse.statuses:type_name -> evnode.v1.FilterStatus
	1,  // 3: evnode.v1.ExecutorService.InitChain:input_type -> evnode.v1.InitChainRequest
	3,  // 4: evnode.v1.ExecutorService.GetTxs:input_type -> evnode.v1.GetTxsRequest
	5,  // 5: evnode.v1.ExecutorService.ExecuteTxs:input_type -> evnode.v1.ExecuteTxsRequest
	7,  // 6: evnode.v1.ExecutorService.SetFinal:input_type -> evnode.v1.SetFinalRequest
	9,  // 7: evnode.v1.ExecutorService.GetExecutionInfo:input_type -> evnode.v1.GetExecutionInfoRequest
	11, // 8: evnode.v1.ExecutorService.FilterTxs:input_type -> evnode.v1.FilterTxsRequest
	2,  // 9: evnode.v1.ExecutorService.InitChain:output_type -> evnode.v1.InitChainResponse
	4,  // 10: evnode.v1.ExecutorService.GetTxs:output_type -> evnode.v1.GetTxsResponse
	6,  // 11: evnode.v1.ExecutorService.ExecuteTxs:output_type -> evnode.v1.ExecuteTxsResponse
	8,  // 12: evnode.v1.ExecutorService.SetFinal:output_type -> evnode.v1.SetFinalResponse
	10, // 13: evnode.v1.ExecutorService.GetExecutionInfo:output_type -> evnode.v1.GetExecutionInfoResponse
	12, // 14: evnode.v1.ExecutorService.FilterTxs:output_type -> evnode.v1.FilterTxsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_evnode_v1_execution_proto_init() }
func file_evnode_v1_execution_proto_init() {
	if File_evnode_v1_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evnode_v1_execution_proto_rawDesc), len(file_evnode_v1_execution_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evnode_v1_execution_proto_goTypes,
		DependencyIndexes: file_evnode_v1_execution_proto_depIdxs,
		EnumInfos:         file_evnode_v1_execution_proto_enumTypes,
		MessageInfos:      file_evnode_v1_execution_proto_msgTypes,
	}.Build()
	File_evnode_v1_execution_proto = out.File
	file_evnode_v1_execution_proto_goTypes = nil
	file_evnode_v1_execution_proto_depIdxs = nil
}
