// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: evnode/v1/state_rpc.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Block contains all the components of a complete block
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *SignedHeader          `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_evnode_v1_state_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetHeader() *SignedHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetBlockRequest defines the request for retrieving a block
type GetBlockRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The height or hash of the block to retrieve
	//
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetBlockRequest_Height
	//	*GetBlockRequest_Hash
	Identifier    isGetBlockRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_evnode_v1_state_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetBlockRequest) GetIdentifier() isGetBlockRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetBlockRequest) GetHeight() uint64 {
	if x != nil {
		if x, ok := x.Identifier.(*GetBlockRequest_Height); ok {
			return x.Height
		}
	}
	return 0
}

func (x *GetBlockRequest) GetHash() []byte {
	if x != nil {
		if x, ok := x.Identifier.(*GetBlockRequest_Hash); ok {
			return x.Hash
		}
	}
	return nil
}

type isGetBlockRequest_Identifier interface {
	isGetBlockRequest_Identifier()
}

type GetBlockRequest_Height struct {
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3,oneof"`
}

type GetBlockRequest_Hash struct {
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3,oneof"`
}

func (*GetBlockRequest_Height) isGetBlockRequest_Identifier() {}

func (*GetBlockRequest_Hash) isGetBlockRequest_Identifier() {}

// GetBlockResponse defines the response for retrieving a block
type GetBlockResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Block          *Block                 `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	HeaderDaHeight uint64                 `protobuf:"varint,2,opt,name=header_da_height,json=headerDaHeight,proto3" json:"header_da_height,omitempty"`
	DataDaHeight   uint64                 `protobuf:"varint,3,opt,name=data_da_height,json=dataDaHeight,proto3" json:"data_da_height,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetBlockResponse) Reset() {
	*x = GetBlockResponse{}
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockResponse) ProtoMessage() {}

func (x *GetBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockResponse.ProtoReflect.Descriptor instead.
func (*GetBlockResponse) Descriptor() ([]byte, []int) {
	return file_evnode_v1_state_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlockResponse) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *GetBlockResponse) GetHeaderDaHeight() uint64 {
	if x != nil {
		return x.HeaderDaHeight
	}
	return 0
}

func (x *GetBlockResponse) GetDataDaHeight() uint64 {
	if x != nil {
		return x.DataDaHeight
	}
	return 0
}

// GetStateResponse defines the response for retrieving the current state
type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *State                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_evnode_v1_state_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetStateResponse) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

// GetMetadataRequest defines the request for retrieving metadata by key
type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_evnode_v1_state_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *GetMetadataRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// GetMetadataResponse defines the response for retrieving metadata
type GetMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_evnode_v1_state_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetMetadataResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// GetGenesisDaHeightResponse defines the DA height at which the first Evolve block was included.
type GetGenesisDaHeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenesisDaHeightResponse) Reset() {
	*x = GetGenesisDaHeightResponse{}
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenesisDaHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenesisDaHeightResponse) ProtoMessage() {}

func (x *GetGenesisDaHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenesisDaHeightResponse.ProtoReflect.Descriptor instead.
func (*GetGenesisDaHeightResponse) Descriptor() ([]byte, []int) {
	return file_evnode_v1_state_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *GetGenesisDaHeightResponse) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

// P2PStoreEntry captures a single head or tail record from a go-header store.
type P2PStoreEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PStoreEntry) Reset() {
	*x = P2PStoreEntry{}
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PStoreEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PStoreEntry) ProtoMessage() {}

func (x *P2PStoreEntry) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PStoreEntry.ProtoReflect.Descriptor instead.
func (*P2PStoreEntry) Descriptor() ([]byte, []int) {
	return file_evnode_v1_state_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *P2PStoreEntry) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *P2PStoreEntry) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *P2PStoreEntry) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

// P2PStoreSnapshot provides head/tail status for a go-header store.
type P2PStoreSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Height        uint64                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Head          *P2PStoreEntry         `protobuf:"bytes,4,opt,name=head,proto3" json:"head,omitempty"`
	Tail          *P2PStoreEntry         `protobuf:"bytes,6,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PStoreSnapshot) Reset() {
	*x = P2PStoreSnapshot{}
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PStoreSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PStoreSnapshot) ProtoMessage() {}

func (x *P2PStoreSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PStoreSnapshot.ProtoReflect.Descriptor instead.
func (*P2PStoreSnapshot) Descriptor() ([]byte, []int) {
	return file_evnode_v1_state_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *P2PStoreSnapshot) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *P2PStoreSnapshot) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *P2PStoreSnapshot) GetHead() *P2PStoreEntry {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *P2PStoreSnapshot) GetTail() *P2PStoreEntry {
	if x != nil {
		return x.Tail
	}
	return nil
}

// GetP2PStoreInfoResponse holds the snapshots for configured go-header stores.
type GetP2PStoreInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stores        []*P2PStoreSnapshot    `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetP2PStoreInfoResponse) Reset() {
	*x = GetP2PStoreInfoResponse{}
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetP2PStoreInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetP2PStoreInfoResponse) ProtoMessage() {}

func (x *GetP2PStoreInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_state_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetP2PStoreInfoResponse.ProtoReflect.Descriptor instead.
func (*GetP2PStoreInfoResponse) Descriptor() ([]byte, []int) {
	return file_evnode_v1_state_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *GetP2PStoreInfoResponse) GetStores() []*P2PStoreSnapshot {
	if x != nil {
		return x.Stores
	}
	return nil
}

var File_evnode_v1_state_rpc_proto protoreflect.FileDescriptor

const file_evnode_v1_state_rpc_proto_rawDesc = "" +
	"\n" +
	"\x19evnode/v1/state_rpc.proto\x12\tevnode.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16evnode/v1/evnode.proto\x1a\x15evnode/v1/state.proto\"]\n" +
	"\x05Block\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.evnode.v1.SignedHeaderR\x06header\x12#\n" +
	"\x04data\x18\x02 \x01(\v2\x0f.evnode.v1.DataR\x04data\"O\n" +
	"\x0fGetBlockRequest\x12\x18\n" +
	"\x06height\x18\x01 \x01(\x04H\x00R\x06height\x12\x14\n" +
	"\x04hash\x18\x02 \x01(\fH\x00R\x04hashB\f\n" +
	"\n" +
	"identifier\"\x8a\x01\n" +
	"\x10GetBlockResponse\x12&\n" +
	"\x05block\x18\x01 \x01(\v2\x10.evnode.v1.BlockR\x05block\x12(\n" +
	"\x10header_da_height\x18\x02 \x01(\x04R\x0eheaderDaHeight\x12$\n" +
	"\x0edata_da_height\x18\x03 \x01(\x04R\fdataDaHeight\":\n" +
	"\x10GetStateResponse\x12&\n" +
	"\x05state\x18\x01 \x01(\v2\x10.evnode.v1.StateR\x05state\"&\n" +
	"\x12GetMetadataRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"+\n" +
	"\x13GetMetadataResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"4\n" +
	"\x1aGetGenesisDaHeightResponse\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x04R\x06height\"k\n" +
	"\rP2PStoreEntry\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"\x9c\x01\n" +
	"\x10P2PStoreSnapshot\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x04R\x06height\x12,\n" +
	"\x04head\x18\x04 \x01(\v2\x18.evnode.v1.P2PStoreEntryR\x04head\x12,\n" +
	"\x04tail\x18\x06 \x01(\v2\x18.evnode.v1.P2PStoreEntryR\x04tail\"N\n" +
	"\x17GetP2PStoreInfoResponse\x123\n" +
	"\x06stores\x18\x01 \x03(\v2\x1b.evnode.v1.P2PStoreSnapshotR\x06stores2\x90\x03\n" +
	"\fStoreService\x12E\n" +
	"\bGetBlock\x12\x1a.evnode.v1.GetBlockRequest\x1a\x1b.evnode.v1.GetBlockResponse\"\x00\x12A\n" +
	"\bGetState\x12\x16.google.protobuf.Empty\x1a\x1b.evnode.v1.GetStateResponse\"\x00\x12N\n" +
	"\vGetMetadata\x12\x1d.evnode.v1.GetMetadataRequest\x1a\x1e.evnode.v1.GetMetadataResponse\"\x00\x12U\n" +
	"\x12GetGenesisDaHeight\x12\x16.google.protobuf.Empty\x1a%.evnode.v1.GetGenesisDaHeightResponse\"\x00\x12O\n" +
	"\x0fGetP2PStoreInfo\x12\x16.google.protobuf.Empty\x1a\".evnode.v1.GetP2PStoreInfoResponse\"\x00B/Z-github.com/evstack/ev-node/types/pb/evnode/v1b\x06proto3"

var (
	file_evnode_v1_state_rpc_proto_rawDescOnce sync.Once
	file_evnode_v1_state_rpc_proto_rawDescData []byte
)

func file_evnode_v1_state_rpc_proto_rawDescGZIP() []byte {
	file_evnode_v1_state_rpc_proto_rawDescOnce.Do(func() {
		file_evnode_v1_state_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evnode_v1_state_rpc_proto_rawDesc), len(file_evnode_v1_state_rpc_proto_rawDesc)))
	})
	return file_evnode_v1_state_rpc_proto_rawDescData
}

var file_evnode_v1_state_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_evnode_v1_state_rpc_proto_goTypes = []any{
	(*Block)(nil),                      // 0: evnode.v1.Block
	(*GetBlockRequest)(nil),            // 1: evnode.v1.GetBlockRequest
	(*GetBlockResponse)(nil),           // 2: evnode.v1.GetBlockResponse
	(*GetStateResponse)(nil),           // 3: evnode.v1.GetStateResponse
	(*GetMetadataRequest)(nil),         // 4: evnode.v1.GetMetadataRequest
	(*GetMetadataResponse)(nil),        // 5: evnode.v1.GetMetadataResponse
	(*GetGenesisDaHeightResponse)(nil), // 6: evnode.v1.GetGenesisDaHeightResponse
	(*P2PStoreEntry)(nil),              // 7: evnode.v1.P2PStoreEntry
	(*P2PStoreSnapshot)(nil),           // 8: evnode.v1.P2PStoreSnapshot
	(*GetP2PStoreInfoResponse)(nil),    // 9: evnode.v1.GetP2PStoreInfoResponse
	(*SignedHeader)(nil),               // 10: evnode.v1.SignedHeader
	(*Data)(nil),                       // 11: evnode.v1.Data
	(*State)(nil),                      // 12: evnode.v1.State
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 14: google.protobuf.Empty
}
var file_evnode_v1_state_rpc_proto_depIdxs = []int32{
	10, // 0: evnode.v1.Block.header:type_name -> evnode.v1.SignedHeader
	11, // 1: evnode.v1.Block.data:type_name -> evnode.v1.Data
	0,  // 2: evnode.v1.GetBlockResponse.block:type_name -> evnode.v1.Block
	12, // 3: evnode.v1.GetStateResponse.state:type_name -> evnode.v1.State
	13, // 4: evnode.v1.P2PStoreEntry.time:type_name -> google.protobuf.Timestamp
	7,  // 5: evnode.v1.P2PStoreSnapshot.head:type_name -> evnode.v1.P2PStoreEntry
	7,  // 6: evnode.v1.P2PStoreSnapshot.tail:type_name -> evnode.v1.P2PStoreEntry
	8,  // 7: evnode.v1.GetP2PStoreInfoResponse.stores:type_name -> evnode.v1.P2PStoreSnapshot
	1,  // 8: evnode.v1.StoreService.GetBlock:input_type -> evnode.v1.GetBlockRequest
	14, // 9: evnode.v1.StoreService.GetState:input_type -> google.protobuf.Empty
	4,  // 10: evnode.v1.StoreService.GetMetadata:input_type -> evnode.v1.GetMetadataRequest
	14, // 11: evnode.v1.StoreService.GetGenesisDaHeight:input_type -> google.protobuf.Empty
	14, // 12: evnode.v1.StoreService.GetP2PStoreInfo:input_type -> google.protobuf.Empty
	2,  // 13: evnode.v1.StoreService.GetBlock:output_type -> evnode.v1.GetBlockResponse
	3,  // 14: evnode.v1.StoreService.GetState:output_type -> evnode.v1.GetStateResponse
	5,  // 15: evnode.v1.StoreService.GetMetadata:output_type -> evnode.v1.GetMetadataResponse
	6,  // 16: evnode.v1.StoreService.GetGenesisDaHeight:output_type -> evnode.v1.GetGenesisDaHeightResponse
	9,  // 17: evnode.v1.StoreService.GetP2PStoreInfo:output_type -> evnode.v1.GetP2PStoreInfoResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_evnode_v1_state_rpc_proto_init() }
func file_evnode_v1_state_rpc_proto_init() {
	if File_evnode_v1_state_rpc_proto != nil {
		return
	}
	file_evnode_v1_evnode_proto_init()
	file_evnode_v1_state_proto_init()
	file_evnode_v1_state_rpc_proto_msgTypes[1].OneofWrappers = []any{
		(*GetBlockRequest_Height)(nil),
		(*GetBlockRequest_Hash)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evnode_v1_state_rpc_proto_rawDesc), len(file_evnode_v1_state_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evnode_v1_state_rpc_proto_goTypes,
		DependencyIndexes: file_evnode_v1_state_rpc_proto_depIdxs,
		MessageInfos:      file_evnode_v1_state_rpc_proto_msgTypes,
	}.Build()
	File_evnode_v1_state_rpc_proto = out.File
	file_evnode_v1_state_rpc_proto_goTypes = nil
	file_evnode_v1_state_rpc_proto_depIdxs = nil
}
