// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: evnode/v1/state.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State is the state of the blockchain.
type State struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         *Version               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ChainId         string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	InitialHeight   uint64                 `protobuf:"varint,3,opt,name=initial_height,json=initialHeight,proto3" json:"initial_height,omitempty"`
	LastBlockHeight uint64                 `protobuf:"varint,4,opt,name=last_block_height,json=lastBlockHeight,proto3" json:"last_block_height,omitempty"`
	LastBlockTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_block_time,json=lastBlockTime,proto3" json:"last_block_time,omitempty"`
	DaHeight        uint64                 `protobuf:"varint,6,opt,name=da_height,json=daHeight,proto3" json:"da_height,omitempty"`
	AppHash         []byte                 `protobuf:"bytes,8,opt,name=app_hash,json=appHash,proto3" json:"app_hash,omitempty"`
	LastHeaderHash  []byte                 `protobuf:"bytes,9,opt,name=last_header_hash,json=lastHeaderHash,proto3" json:"last_header_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_evnode_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_evnode_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *State) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *State) GetInitialHeight() uint64 {
	if x != nil {
		return x.InitialHeight
	}
	return 0
}

func (x *State) GetLastBlockHeight() uint64 {
	if x != nil {
		return x.LastBlockHeight
	}
	return 0
}

func (x *State) GetLastBlockTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastBlockTime
	}
	return nil
}

func (x *State) GetDaHeight() uint64 {
	if x != nil {
		return x.DaHeight
	}
	return 0
}

func (x *State) GetAppHash() []byte {
	if x != nil {
		return x.AppHash
	}
	return nil
}

func (x *State) GetLastHeaderHash() []byte {
	if x != nil {
		return x.LastHeaderHash
	}
	return nil
}

// SequencerDACheckpoint tracks the position in the DA where transactions were last processed
type SequencerDACheckpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DA block height being processed
	DaHeight uint64 `protobuf:"varint,1,opt,name=da_height,json=daHeight,proto3" json:"da_height,omitempty"`
	// Index of the next transaction to process within the DA block's forced inclusion batch
	TxIndex       uint64 `protobuf:"varint,2,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequencerDACheckpoint) Reset() {
	*x = SequencerDACheckpoint{}
	mi := &file_evnode_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequencerDACheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequencerDACheckpoint) ProtoMessage() {}

func (x *SequencerDACheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequencerDACheckpoint.ProtoReflect.Descriptor instead.
func (*SequencerDACheckpoint) Descriptor() ([]byte, []int) {
	return file_evnode_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *SequencerDACheckpoint) GetDaHeight() uint64 {
	if x != nil {
		return x.DaHeight
	}
	return 0
}

func (x *SequencerDACheckpoint) GetTxIndex() uint64 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

// ExecMeta tracks execution state per height for idempotent execution.
// This enables crash recovery and prevents sibling block creation on retries.
type ExecMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block height this execution metadata is for
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// EL parent block hash used for this execution
	ParentHash []byte `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	// Engine API payload ID (optional, set after forkchoiceUpdatedV3)
	PayloadId []byte `protobuf:"bytes,3,opt,name=payload_id,json=payloadId,proto3" json:"payload_id,omitempty"`
	// EL block hash once built (set after getPayloadV4)
	BlockHash []byte `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// State root from the execution payload
	StateRoot []byte `protobuf:"bytes,5,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	// Hash of the transaction list for sanity checks
	TxHash []byte `protobuf:"bytes,6,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// Block timestamp
	Timestamp int64 `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Current execution stage: "started", "built", "submitted", "promoted"
	Stage string `protobuf:"bytes,8,opt,name=stage,proto3" json:"stage,omitempty"`
	// Unix timestamp when this metadata was last updated
	UpdatedAtUnix int64 `protobuf:"varint,9,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecMeta) Reset() {
	*x = ExecMeta{}
	mi := &file_evnode_v1_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecMeta) ProtoMessage() {}

func (x *ExecMeta) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecMeta.ProtoReflect.Descriptor instead.
func (*ExecMeta) Descriptor() ([]byte, []int) {
	return file_evnode_v1_state_proto_rawDescGZIP(), []int{2}
}

func (x *ExecMeta) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ExecMeta) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecMeta) GetPayloadId() []byte {
	if x != nil {
		return x.PayloadId
	}
	return nil
}

func (x *ExecMeta) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ExecMeta) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *ExecMeta) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *ExecMeta) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExecMeta) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ExecMeta) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

var File_evnode_v1_state_proto protoreflect.FileDescriptor

const file_evnode_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x15evnode/v1/state.proto\x12\tevnode.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16evnode/v1/evnode.proto\"\xcf\x02\n" +
	"\x05State\x12,\n" +
	"\aversion\x18\x01 \x01(\v2\x12.evnode.v1.VersionR\aversion\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12%\n" +
	"\x0einitial_height\x18\x03 \x01(\x04R\rinitialHeight\x12*\n" +
	"\x11last_block_height\x18\x04 \x01(\x04R\x0flastBlockHeight\x12B\n" +
	"\x0flast_block_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rlastBlockTime\x12\x1b\n" +
	"\tda_height\x18\x06 \x01(\x04R\bdaHeight\x12\x19\n" +
	"\bapp_hash\x18\b \x01(\fR\aappHash\x12(\n" +
	"\x10last_header_hash\x18\t \x01(\fR\x0elastHeaderHashJ\x04\b\a\x10\b\"O\n" +
	"\x15SequencerDACheckpoint\x12\x1b\n" +
	"\tda_height\x18\x01 \x01(\x04R\bdaHeight\x12\x19\n" +
	"\btx_index\x18\x02 \x01(\x04R\atxIndex\"\x95\x02\n" +
	"\bExecMeta\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1f\n" +
	"\vparent_hash\x18\x02 \x01(\fR\n" +
	"parentHash\x12\x1d\n" +
	"\n" +
	"payload_id\x18\x03 \x01(\fR\tpayloadId\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x04 \x01(\fR\tblockHash\x12\x1d\n" +
	"\n" +
	"state_root\x18\x05 \x01(\fR\tstateRoot\x12\x17\n" +
	"\atx_hash\x18\x06 \x01(\fR\x06txHash\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05stage\x18\b \x01(\tR\x05stage\x12&\n" +
	"\x0fupdated_at_unix\x18\t \x01(\x03R\rupdatedAtUnixB/Z-github.com/evstack/ev-node/types/pb/evnode/v1b\x06proto3"

var (
	file_evnode_v1_state_proto_rawDescOnce sync.Once
	file_evnode_v1_state_proto_rawDescData []byte
)

func file_evnode_v1_state_proto_rawDescGZIP() []byte {
	file_evnode_v1_state_proto_rawDescOnce.Do(func() {
		file_evnode_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evnode_v1_state_proto_rawDesc), len(file_evnode_v1_state_proto_rawDesc)))
	})
	return file_evnode_v1_state_proto_rawDescData
}

var file_evnode_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_evnode_v1_state_proto_goTypes = []any{
	(*State)(nil),                 // 0: evnode.v1.State
	(*SequencerDACheckpoint)(nil), // 1: evnode.v1.SequencerDACheckpoint
	(*ExecMeta)(nil),              // 2: evnode.v1.ExecMeta
	(*Version)(nil),               // 3: evnode.v1.Version
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_evnode_v1_state_proto_depIdxs = []int32{
	3, // 0: evnode.v1.State.version:type_name -> evnode.v1.Version
	4, // 1: evnode.v1.State.last_block_time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_evnode_v1_state_proto_init() }
func file_evnode_v1_state_proto_init() {
	if File_evnode_v1_state_proto != nil {
		return
	}
	file_evnode_v1_evnode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evnode_v1_state_proto_rawDesc), len(file_evnode_v1_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_evnode_v1_state_proto_goTypes,
		DependencyIndexes: file_evnode_v1_state_proto_depIdxs,
		MessageInfos:      file_evnode_v1_state_proto_msgTypes,
	}.Build()
	File_evnode_v1_state_proto = out.File
	file_evnode_v1_state_proto_goTypes = nil
	file_evnode_v1_state_proto_depIdxs = nil
}
