// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: evnode/v1/state.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State is the state of the blockchain.
type State struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         *Version               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ChainId         string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	InitialHeight   uint64                 `protobuf:"varint,3,opt,name=initial_height,json=initialHeight,proto3" json:"initial_height,omitempty"`
	LastBlockHeight uint64                 `protobuf:"varint,4,opt,name=last_block_height,json=lastBlockHeight,proto3" json:"last_block_height,omitempty"`
	LastBlockTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_block_time,json=lastBlockTime,proto3" json:"last_block_time,omitempty"`
	DaHeight        uint64                 `protobuf:"varint,6,opt,name=da_height,json=daHeight,proto3" json:"da_height,omitempty"`
	AppHash         []byte                 `protobuf:"bytes,8,opt,name=app_hash,json=appHash,proto3" json:"app_hash,omitempty"`
	LastHeaderHash  []byte                 `protobuf:"bytes,9,opt,name=last_header_hash,json=lastHeaderHash,proto3" json:"last_header_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_evnode_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_evnode_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *State) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *State) GetInitialHeight() uint64 {
	if x != nil {
		return x.InitialHeight
	}
	return 0
}

func (x *State) GetLastBlockHeight() uint64 {
	if x != nil {
		return x.LastBlockHeight
	}
	return 0
}

func (x *State) GetLastBlockTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastBlockTime
	}
	return nil
}

func (x *State) GetDaHeight() uint64 {
	if x != nil {
		return x.DaHeight
	}
	return 0
}

func (x *State) GetAppHash() []byte {
	if x != nil {
		return x.AppHash
	}
	return nil
}

func (x *State) GetLastHeaderHash() []byte {
	if x != nil {
		return x.LastHeaderHash
	}
	return nil
}

// SequencerDACheckpoint tracks the position in the DA where transactions were last processed
type SequencerDACheckpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DA block height being processed
	DaHeight uint64 `protobuf:"varint,1,opt,name=da_height,json=daHeight,proto3" json:"da_height,omitempty"`
	// Index of the next transaction to process within the DA block's forced inclusion batch
	TxIndex       uint64 `protobuf:"varint,2,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequencerDACheckpoint) Reset() {
	*x = SequencerDACheckpoint{}
	mi := &file_evnode_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequencerDACheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequencerDACheckpoint) ProtoMessage() {}

func (x *SequencerDACheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequencerDACheckpoint.ProtoReflect.Descriptor instead.
func (*SequencerDACheckpoint) Descriptor() ([]byte, []int) {
	return file_evnode_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *SequencerDACheckpoint) GetDaHeight() uint64 {
	if x != nil {
		return x.DaHeight
	}
	return 0
}

func (x *SequencerDACheckpoint) GetTxIndex() uint64 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

// Tx represents a transaction with its raw data
type Tx struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tx) Reset() {
	*x = Tx{}
	mi := &file_evnode_v1_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tx) ProtoMessage() {}

func (x *Tx) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tx.ProtoReflect.Descriptor instead.
func (*Tx) Descriptor() ([]byte, []int) {
	return file_evnode_v1_state_proto_rawDescGZIP(), []int{2}
}

func (x *Tx) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_evnode_v1_state_proto protoreflect.FileDescriptor

const file_evnode_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x15evnode/v1/state.proto\x12\tevnode.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16evnode/v1/evnode.proto\"\xcf\x02\n" +
	"\x05State\x12,\n" +
	"\aversion\x18\x01 \x01(\v2\x12.evnode.v1.VersionR\aversion\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12%\n" +
	"\x0einitial_height\x18\x03 \x01(\x04R\rinitialHeight\x12*\n" +
	"\x11last_block_height\x18\x04 \x01(\x04R\x0flastBlockHeight\x12B\n" +
	"\x0flast_block_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rlastBlockTime\x12\x1b\n" +
	"\tda_height\x18\x06 \x01(\x04R\bdaHeight\x12\x19\n" +
	"\bapp_hash\x18\b \x01(\fR\aappHash\x12(\n" +
	"\x10last_header_hash\x18\t \x01(\fR\x0elastHeaderHashJ\x04\b\a\x10\b\"O\n" +
	"\x15SequencerDACheckpoint\x12\x1b\n" +
	"\tda_height\x18\x01 \x01(\x04R\bdaHeight\x12\x19\n" +
	"\btx_index\x18\x02 \x01(\x04R\atxIndex\"\x18\n" +
	"\x02Tx\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04dataB/Z-github.com/evstack/ev-node/types/pb/evnode/v1b\x06proto3"

var (
	file_evnode_v1_state_proto_rawDescOnce sync.Once
	file_evnode_v1_state_proto_rawDescData []byte
)

func file_evnode_v1_state_proto_rawDescGZIP() []byte {
	file_evnode_v1_state_proto_rawDescOnce.Do(func() {
		file_evnode_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evnode_v1_state_proto_rawDesc), len(file_evnode_v1_state_proto_rawDesc)))
	})
	return file_evnode_v1_state_proto_rawDescData
}

var file_evnode_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_evnode_v1_state_proto_goTypes = []any{
	(*State)(nil),                 // 0: evnode.v1.State
	(*SequencerDACheckpoint)(nil), // 1: evnode.v1.SequencerDACheckpoint
	(*Tx)(nil),                    // 2: evnode.v1.Tx
	(*Version)(nil),               // 3: evnode.v1.Version
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_evnode_v1_state_proto_depIdxs = []int32{
	3, // 0: evnode.v1.State.version:type_name -> evnode.v1.Version
	4, // 1: evnode.v1.State.last_block_time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_evnode_v1_state_proto_init() }
func file_evnode_v1_state_proto_init() {
	if File_evnode_v1_state_proto != nil {
		return
	}
	file_evnode_v1_evnode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evnode_v1_state_proto_rawDesc), len(file_evnode_v1_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_evnode_v1_state_proto_goTypes,
		DependencyIndexes: file_evnode_v1_state_proto_depIdxs,
		MessageInfos:      file_evnode_v1_state_proto_msgTypes,
	}.Build()
	File_evnode_v1_state_proto = out.File
	file_evnode_v1_state_proto_goTypes = nil
	file_evnode_v1_state_proto_depIdxs = nil
}
