[book]
authors = ["Rollkit"]
language = "en"
multilingual = false
src = "src"
title = "Rollkit Specifications"

[output.html]
git-repository-url = "https://github.com/rollkit/rollkit"

[rust]
edition = "2021"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
