name: Docker Build & Publish

# Trigger on all push events, new semantic version tags, and all PRs
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:

jobs:
  git_diff:
    uses: technote-space/get-diff-action@v6.1.2
    with:
      PATTERNS: |
        **/**.go
        go.mod
        go.sum

  rollkit-docker:
    name: rollkit-docker
    if: env.GIT_DIFF
    permissions:
      contents: write
      packages: write
    uses: rollkit/.github/.github/workflows/reusable_dockerfile_pipeline.yml@v0.5.0
    with:
      dockerfile: Dockerfile
      secrets: inherit
