name: Docs Build
permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
  pull_request:
    paths:
      - "docs/**"

jobs:
  docs_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn # or pnpm / npm
          cache-dependency-path: docs/yarn.lock
      - name: Install dependencies
        run: yarn install # or pnpm install / npm ci
        working-directory: docs
      - name: Build with VitePress
        run: yarn build # or pnpm build / npm build
        working-directory: docs
