name: Publish Rust Crates

on:
  push:
    tags:
      - "rust-v*"
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Perform a dry run without publishing"
        required: false
        type: boolean
        default: true

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: ./.github/actions/rust-setup
        with:
          cache-key: publish

      - name: Check crate versions
        run: |
          echo "=== Checking crate versions ==="
          echo "types version: $(cargo pkgid -p ev-types | cut -d# -f2)"
          echo "ev-client version: $(cargo pkgid -p ev-client | cut -d# -f2)"

      - name: Run tests
        run: cargo test --workspace --all-features

      - name: Package and publish ev-types (dry run)
        if: github.event_name == 'workflow_dispatch' && inputs.dry_run
        run: |
          cd client/crates/types
          cargo package --allow-dirty
          cargo publish --dry-run

      - name: Package and publish ev-client (dry run)
        if: github.event_name == 'workflow_dispatch' && inputs.dry_run
        run: |
          cd client/crates/client
          cargo package --allow-dirty
          cargo publish --dry-run

      - name: Publish ev-types
        if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) || (github.event_name == 'workflow_dispatch' && !inputs.dry_run)
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cd client/crates/types
          cargo package --allow-dirty
          cargo publish

      - name: Wait for ev-types to be available
        if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) || (github.event_name == 'workflow_dispatch' && !inputs.dry_run)
        run: |
          echo "Waiting for ev-types to be available on crates.io..."
          sleep 60
          # Verify the package is available
          cargo search ev-types --limit 1

      - name: Publish ev-client
        if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) || (github.event_name == 'workflow_dispatch' && !inputs.dry_run)
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cd client/crates/client
          cargo package --allow-dirty
          cargo publish

      - name: Create GitHub Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          name: Rust Client ${{ github.ref_name }}
          body: |
            # Rust Client Release

            This release includes:
            - `ev-types`: Proto-generated types for ev-node
            - `ev-client`: High-level Rust client for ev-node gRPC services

            ## Installation

            Add to your `Cargo.toml`:
            ```toml
            [dependencies]
            ev-client = "<version>"
            ```

            See the [README](https://github.com/evstack/ev-node/tree/main/client/crates/client) for usage examples.
          draft: false
          prerelease: false
