name: Specs Deploy

on:
  push:
    branches:
      - main
    paths:
      - specs/**
  pull_request:
    paths:
      - specs/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "0.4.21"

      - name: Build book
        run: mdbook build specs

      - name: Deploy main
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./specs/book
          # keep_files is to prevent PR preview files from being overwritten.
          # If we need to overwrite such files, trigger this workflow manually.
          keep_files: ${{ github.event_name != 'workflow_dispatch' }}
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
            PATTERNS: |
              specs/**
      - name: Deploy PR preview
        # Only run this job if the PR was created from a branch on
        # rollkit/rollkit because this job will fail for branches from forks.
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository && env.GIT_DIFF
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./specs/book

